import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  reactStrictMode: true,
  experimental: {
    optimizePackageImports: ["lucide-react", "three"],
  },
  images: {
    remotePatterns: [
      { protocol: "https", hostname: "nescodigital.com" },
      { protocol: "https", hostname: "i0.wp.com" },
      { protocol: "https", hostname: "i.pravatar.cc" },
      { protocol: "https", hostname: "randomuser.me" },
    ],
    formats: ["image/avif", "image/webp"],
  },
  async redirects() {
    return [
      // 404 URLs - old WordPress pages
      { source: '/ro/projects/watchmaker', destination: '/proiecte', permanent: true },
      { source: '/en/digital-marketing-services/social-marketing-en', destination: '/en/digital-marketing', permanent: true },
      { source: '/en/services/content-marketing', destination: '/en/digital-marketing', permanent: true },
      { source: '/en/custom-magento-online-store', destination: '/en/webdesign', permanent: true },
      { source: '/ro/servicii-marketing/audit-digital', destination: '/marketing-digital', permanent: true },
      { source: '/ro/servicii-marketing/influencer-marketing-ro', destination: '/marketing-digital', permanent: true },
      { source: '/ro/projects/luxury-interiors-2', destination: '/proiecte', permanent: true },
      { source: '/ro/servicii-marketing/performance-marketing-ro', destination: '/reclame-platite', permanent: true },
      { source: '/ro/projects/monica-georoceanu-ro', destination: '/proiecte', permanent: true },
      { source: '/ro/projects/strategie-digitala-si-dezvoltare-web', destination: '/proiecte', permanent: true },
      { source: '/ro/projects/urbangang-com-2', destination: '/proiecte', permanent: true },
      { source: '/ro/servicii-marketing/cro-optimizarea-ratei-de-conversie', destination: '/solutii-cro-ro', permanent: true },
      { source: '/ro/projects/bellacasa-residence-ro', destination: '/proiecte', permanent: true },
      { source: '/ro/despre-noi', destination: '/despre-nesco-digital', permanent: true },
      { source: '/ro/servicii-marketing', destination: '/marketing-digital', permanent: true },
      { source: '/services/technology-architecture', destination: '/marketing-digital', permanent: true },
      { source: '/services/digital-transformation-consulting', destination: '/marketing-digital', permanent: true },
      { source: '/services/visual-identity', destination: '/marketing-digital', permanent: true },
      { source: '/services/marketing-automation', destination: '/solutii-email-marketing-ro', permanent: true },
      { source: '/ro/start-proiect', destination: '/contact', permanent: true },
      { source: '/en/facebook-ads-en', destination: '/en/paid-ads', permanent: true },
      { source: '/servicii-marketing/audit-digital', destination: '/marketing-digital', permanent: true },
      { source: '/ro/projects/campanie-employer-branding', destination: '/proiecte', permanent: true },
      { source: '/servicii-marketing-digital/strategie-de-brand', destination: '/strategie-digitala-ro', permanent: true },
      { source: '/instagram-ads-campaigns', destination: '/reclame-platite', permanent: true },
      { source: '/en/google-ads-campaigns', destination: '/en/paid-ads', permanent: true },
      { source: '/en/services', destination: '/en/digital-marketing', permanent: true },
      { source: '/en/premium-business-website', destination: '/en/webdesign', permanent: true },
      { source: '/services/website-development', destination: '/webdesign', permanent: true },
      { source: '/services/ecommerce', destination: '/magazine-online-ro', permanent: true },
      { source: '/about-us', destination: '/despre-nesco-digital', permanent: true },
      { source: '/en/digital-marketing-services/naming-taglines', destination: '/en/digital-marketing', permanent: true },
      { source: '/en/digital-marketing-services/digital-auditing-solutions', destination: '/en/digital-marketing', permanent: true },
      { source: '/instagram-ads', destination: '/reclame-platite', permanent: true },
      { source: '/services/brand-collateral', destination: '/marketing-digital', permanent: true },
      { source: '/services/digital-auditing', destination: '/marketing-digital', permanent: true },
      { source: '/en/tiktok-en', destination: '/en/paid-ads', permanent: true },
      { source: '/en/facebook-en', destination: '/en/paid-ads', permanent: true },
      { source: '/en/lead-generation-website-en', destination: '/en/webdesign', permanent: true },
      { source: '/en/digital-marketing-services/influencer-marketing', destination: '/en/digital-marketing', permanent: true },
      { source: '/en/project-type/visual', destination: '/en/projects', permanent: true },
      { source: '/en/website-maintenance', destination: '/en/webdesign', permanent: true },
      { source: '/2021-guide-to-google-display-ad-sizes', destination: '/blog', permanent: true },
      { source: '/ways-to-improve-your-customer-relationships-with-marketing-automation', destination: '/blog', permanent: true },
      { source: '/ro/servicii-marketing/nume-slogan-de-brand', destination: '/marketing-digital', permanent: true },
      { source: '/servicii-marketing-digital/marketing-automatizat', destination: '/solutii-email-marketing-ro', permanent: true },
      { source: '/projects/space-philosophy-en', destination: '/proiecte', permanent: true },
      { source: '/en/projects/bellacasa-ro-web-development', destination: '/en/projects', permanent: true },

      // Redirects with wrong format (no trailing slash etc)
      { source: '/services/digital-strategy', destination: '/strategie-digitala-ro', permanent: true },
      { source: '/google-ads', destination: '/reclame-platite', permanent: true },
      { source: '/lets-talk', destination: '/contact', permanent: true },
      { source: '/instagram-en', destination: '/en/paid-ads', permanent: true },
      { source: '/google-de', destination: '/ge/bezahlte-werbung', permanent: true },
      { source: '/linkedin-de', destination: '/ge/bezahlte-werbung', permanent: true },
      { source: '/instagram-de', destination: '/ge/bezahlte-werbung', permanent: true },
      { source: '/facebook-de', destination: '/ge/bezahlte-werbung', permanent: true },
      { source: '/tiktok-de', destination: '/ge/bezahlte-werbung', permanent: true },
      { source: '/de', destination: '/ge', permanent: true },
      { source: '/ro', destination: '/', permanent: true },
      { source: '/en', destination: '/en', permanent: false },
      { source: '/tiktok-en', destination: '/en/paid-ads', permanent: true },
      { source: '/facebook-en', destination: '/en/paid-ads', permanent: true },
      { source: '/servicii-marketing-digital/strategie-digitala', destination: '/strategie-digitala-ro', permanent: true },
      { source: '/tiktok-ro', destination: '/reclame-platite', permanent: true },
      { source: '/en/digital-marketing-services/digital-strategy', destination: '/en/digital-marketing', permanent: true },
      { source: '/linkedin-en', destination: '/en/paid-ads', permanent: true },
      { source: '/instagram-ro', destination: '/reclame-platite', permanent: true },
      { source: '/google-ro', destination: '/reclame-platite', permanent: true },
      { source: '/en/services/digital-strategy', destination: '/en/digital-marketing', permanent: true },
      { source: '/linkedin-ro', destination: '/reclame-platite', permanent: true },
      { source: '/google-en', destination: '/en/paid-ads', permanent: true },
      { source: '/facebook-ro', destination: '/reclame-platite', permanent: true },
      { source: '/ro/proiecte', destination: '/proiecte', permanent: true },
      { source: '/projects', destination: '/proiecte', permanent: true },
      { source: '/ge', destination: '/ge', permanent: false },
      { source: '/Projects', destination: '/proiecte', permanent: true },
      { source: '/en/projects/employer-branding-campaign', destination: '/en/projects', permanent: true },
      { source: '/projects/watchmaker-web', destination: '/proiecte', permanent: true },
      { source: '/en/projects/labianca-architectura', destination: '/en/projects', permanent: true },
      { source: '/en/projects/azzurro', destination: '/en/projects', permanent: true },
      { source: '/projects/azzurro', destination: '/proiecte', permanent: true },
      { source: '/5-relevant-kpis-for-online-lead-generation', destination: '/blog', permanent: true },
      { source: '/author/we_are_nesco', destination: '/', permanent: true },
      { source: '/en/projects/roca-ceramics-csr-en', destination: '/en/projects', permanent: true },
      { source: '/projects/babyphoria', destination: '/proiecte', permanent: true },
      { source: '/en/author/we_are_nesco', destination: '/en', permanent: true },
      { source: '/en/projects/babyphoria', destination: '/en/projects', permanent: true },
      { source: '/ge/author/we_are_nesco', destination: '/ge', permanent: true },
      { source: '/en/projects/luxury-interiors', destination: '/en/projects', permanent: true },
      { source: '/projects/luxury-interiors', destination: '/proiecte', permanent: true },
      { source: '/projects/roca-ceramics-csr-en', destination: '/proiecte', permanent: true },
      { source: '/why-website-maintenance-is-so-important', destination: '/blog', permanent: true },
      { source: '/project-type/visual', destination: '/proiecte', permanent: true },
      { source: '/projects/labianca-architectura', destination: '/proiecte', permanent: true },
      { source: '/project-type/web', destination: '/proiecte', permanent: true },
      { source: '/contact', destination: '/contact', permanent: false },

      // Catch-all patterns
      { source: '/services/:slug*', destination: '/marketing-digital', permanent: true },
      { source: '/ro/:slug*', destination: '/', permanent: true },
      { source: '/servicii-marketing-digital/:slug*', destination: '/marketing-digital', permanent: true },
      { source: '/en/projects/:slug*', destination: '/en/projects', permanent: true },
      { source: '/projects/:slug*', destination: '/proiecte', permanent: true },
      { source: '/en/digital-marketing-services/:slug*', destination: '/en/digital-marketing', permanent: true },
    ];
  },
  async headers() {
    return [
      {
        source: "/(.*)",
        headers: [
          { key: "X-Content-Type-Options", value: "nosniff" },
          { key: "X-Frame-Options", value: "DENY" },
          { key: "X-XSS-Protection", value: "1; mode=block" },
          { key: "Referrer-Policy", value: "strict-origin-when-cross-origin" },
        ],
      },
    ];
  },
  // Preserve exact URL structure from existing site
  trailingSlash: true,
};

export default nextConfig;
