import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  reactStrictMode: true,
  experimental: {
    optimizePackageImports: ["lucide-react", "three"],
  },
  images: {
    remotePatterns: [
      { protocol: "https", hostname: "nescodigital.com" },
      { protocol: "https", hostname: "i0.wp.com" },
      { protocol: "https", hostname: "i.pravatar.cc" },
      { protocol: "https", hostname: "randomuser.me" },
    ],
    formats: ["image/avif", "image/webp"],
  },
  async redirects() {
    return [
      // Pagini principale EN
      { source: '/about-us', destination: '/en/about-nesco-digital', permanent: true },
      { source: '/about-us/', destination: '/en/about-nesco-digital', permanent: true },
      { source: '/lets-talk', destination: '/contact', permanent: true },
      { source: '/lets-talk/', destination: '/contact', permanent: true },
      { source: '/projects', destination: '/en/projects', permanent: true },
      { source: '/projects/', destination: '/en/projects', permanent: true },
      { source: '/privacy-policy', destination: '/en/privacy-policy', permanent: true },
      { source: '/privacy-policy/', destination: '/en/privacy-policy', permanent: true },

      // Servicii EN vechi
      { source: '/services/performance-marketing', destination: '/en/paid-ads', permanent: true },
      { source: '/services/performance-marketing/', destination: '/en/paid-ads', permanent: true },
      { source: '/services/social-marketing', destination: '/en/social-media-solutions', permanent: true },
      { source: '/services/social-marketing/', destination: '/en/social-media-solutions', permanent: true },
      { source: '/services/digital-strategy', destination: '/en/digital-strategy', permanent: true },
      { source: '/services/digital-strategy/', destination: '/en/digital-strategy', permanent: true },
      { source: '/services/website-development', destination: '/en/webdesign', permanent: true },
      { source: '/services/website-development/', destination: '/en/webdesign', permanent: true },
      { source: '/services/ecommerce', destination: '/en/e-commerce-stores', permanent: true },
      { source: '/services/ecommerce/', destination: '/en/e-commerce-stores', permanent: true },
      { source: '/services/ecommerce-consulting', destination: '/en/e-commerce-stores', permanent: true },
      { source: '/services/ecommerce-consulting/', destination: '/en/e-commerce-stores', permanent: true },
      { source: '/services/cro-conversion-rate-optimization', destination: '/en/cro-solutions', permanent: true },
      { source: '/services/cro-conversion-rate-optimization/', destination: '/en/cro-solutions', permanent: true },
      { source: '/services/marketing-automation', destination: '/en/email-marketing-solutions', permanent: true },
      { source: '/services/marketing-automation/', destination: '/en/email-marketing-solutions', permanent: true },
      { source: '/services/marketing-strategy', destination: '/en/digital-strategy', permanent: true },
      { source: '/services/marketing-strategy/', destination: '/en/digital-strategy', permanent: true },
      { source: '/services/brand-strategy', destination: '/en/digital-strategy', permanent: true },
      { source: '/services/brand-strategy/', destination: '/en/digital-strategy', permanent: true },
      { source: '/services/digital-transformation-consulting', destination: '/en/digital-strategy', permanent: true },
      { source: '/services/digital-transformation-consulting/', destination: '/en/digital-strategy', permanent: true },
      { source: '/services/digital-auditing', destination: '/en/digital-strategy', permanent: true },
      { source: '/services/digital-auditing/', destination: '/en/digital-strategy', permanent: true },

      // Proiecte EN vechi
      { source: '/projects/space-philosophy-en', destination: '/en/projects', permanent: true },
      { source: '/projects/space-philosophy-en/', destination: '/en/projects', permanent: true },
      { source: '/projects/roca-ceramics-csr-en', destination: '/en/projects', permanent: true },
      { source: '/projects/roca-ceramics-csr-en/', destination: '/en/projects', permanent: true },
      { source: '/projects/sub-zero-wolf-website-en', destination: '/en/projects', permanent: true },
      { source: '/projects/today-x-gladiatorul-en', destination: '/en/projects', permanent: true },
      { source: '/projects/monicageoroceanu-com-en', destination: '/en/projects', permanent: true },
      { source: '/projects/employer-branding-campaign', destination: '/en/projects', permanent: true },
      { source: '/projects/watchmaker-web', destination: '/en/projects', permanent: true },
      { source: '/projects/bellacasa-residence', destination: '/en/projects', permanent: true },
      { source: '/projects/labianca-architectura', destination: '/en/projects', permanent: true },
      { source: '/projects/etq-minimalist-fashion', destination: '/en/projects', permanent: true },
      { source: '/projects/azzurro', destination: '/en/projects', permanent: true },
      { source: '/projects/babyphoria', destination: '/en/projects', permanent: true },
      { source: '/projects/pp-ice-cream', destination: '/en/projects', permanent: true },
      { source: '/projects/various-branding-projects', destination: '/en/projects', permanent: true },
      { source: '/projects/maximize-room-bookings', destination: '/en/projects/crestere-rezervari-accor-hotels', permanent: true },
      { source: '/projects/improved-lead-quality', destination: '/en/projects/imbunatatire-calitate-leaduri-experian', permanent: true },
      { source: '/projects/zahn-pioch-german-dental-clinic', destination: '/en/projects', permanent: true },
      { source: '/projects/web-development-for-hairstyle-brand', destination: '/en/projects', permanent: true },
      { source: '/projects/reaching-new-target-audience', destination: '/en/projects/targetare-public-douglas-cosmetics', permanent: true },
      { source: '/projects/increase-conversion-issues', destination: '/en/projects/remediere-conversie-eyeglasses24', permanent: true },
      { source: '/projects/urbangang-com', destination: '/en/projects', permanent: true },
      { source: '/projects/digital-strategy-and-web-development', destination: '/en/projects', permanent: true },
      { source: '/projects/luxury-interiors', destination: '/en/projects', permanent: true },
      { source: '/projects/bellacasa-ro-web-development', destination: '/en/projects', permanent: true },
      { source: '/projects/roca-w', destination: '/en/projects', permanent: true },
      { source: '/projects/tastimo-app', destination: '/en/projects', permanent: true },
      { source: '/projects/novaintermed-website-proposal', destination: '/en/projects', permanent: true },

      // Pagini RO vechi
      { source: '/ro', destination: '/', permanent: true },
      { source: '/ro/', destination: '/', permanent: true },
      { source: '/ro/despre-noi', destination: '/despre-nesco-digital', permanent: true },
      { source: '/ro/despre-noi/', destination: '/despre-nesco-digital', permanent: true },
      { source: '/ro/proiecte', destination: '/proiecte', permanent: true },
      { source: '/ro/proiecte/', destination: '/proiecte', permanent: true },
      { source: '/ro/start-proiect', destination: '/contact', permanent: true },
      { source: '/ro/start-proiect/', destination: '/contact', permanent: true },
      { source: '/ro/contacteaza-nesco-digital', destination: '/contact', permanent: true },
      { source: '/ro/contacteaza-nesco-digital/', destination: '/contact', permanent: true },

      // Servicii RO vechi
      { source: '/ro/servicii-marketing', destination: '/reclame-platite', permanent: true },
      { source: '/ro/servicii-marketing/', destination: '/reclame-platite', permanent: true },
      { source: '/ro/servicii-marketing/performance-marketing-ro', destination: '/reclame-platite', permanent: true },
      { source: '/ro/servicii-marketing/performance-marketing-ro/', destination: '/reclame-platite', permanent: true },
      { source: '/ro/servicii-marketing/strategie-digitala', destination: '/marketing-digital/strategie-digitala', permanent: true },
      { source: '/ro/servicii-marketing/strategie-digitala/', destination: '/marketing-digital/strategie-digitala', permanent: true },
      { source: '/ro/servicii-marketing/ecommerce-ro', destination: '/webdesign/magazine-online', permanent: true },
      { source: '/ro/servicii-marketing/ecommerce-ro/', destination: '/webdesign/magazine-online', permanent: true },
      { source: '/ro/servicii-marketing/dezvoltare-web', destination: '/webdesign', permanent: true },
      { source: '/ro/servicii-marketing/dezvoltare-web/', destination: '/webdesign', permanent: true },
      { source: '/ro/servicii-marketing/cro-optimizarea-ratei-de-conversie', destination: '/marketing-digital/cro', permanent: true },
      { source: '/ro/servicii-marketing/cro-optimizarea-ratei-de-conversie/', destination: '/marketing-digital/cro', permanent: true },
      { source: '/ro/servicii-marketing/marketing-automatizat', destination: '/marketing-digital/email-marketing', permanent: true },
      { source: '/ro/servicii-marketing/marketing-automatizat/', destination: '/marketing-digital/email-marketing', permanent: true },
      { source: '/ro/servicii-marketing/social-marketing-ro', destination: '/marketing-digital/social-media', permanent: true },
      { source: '/ro/servicii-marketing/social-marketing-ro/', destination: '/marketing-digital/social-media', permanent: true },

      // Proiecte RO vechi
      { source: '/ro/projects/cresterea-numarului-de-rezervari', destination: '/proiecte/crestere-rezervari-accor-hotels', permanent: true },
      { source: '/ro/projects/cresterea-numarului-de-rezervari/', destination: '/proiecte/crestere-rezervari-accor-hotels', permanent: true },
      { source: '/ro/projects/imbunatatirea-calitatii-lead-urilor', destination: '/proiecte/imbunatatire-calitate-leaduri-experian', permanent: true },
      { source: '/ro/projects/imbunatatirea-calitatii-lead-urilor/', destination: '/proiecte/imbunatatire-calitate-leaduri-experian', permanent: true },
      { source: '/ro/projects/targetarea-unui-nou-public-tinta', destination: '/proiecte/targetare-public-douglas-cosmetics', permanent: true },
      { source: '/ro/projects/targetarea-unui-nou-public-tinta/', destination: '/proiecte/targetare-public-douglas-cosmetics', permanent: true },
      { source: '/ro/projects/remediere-probleme-de-conversie', destination: '/proiecte/remediere-conversie-eyeglasses24', permanent: true },
      { source: '/ro/projects/remediere-probleme-de-conversie/', destination: '/proiecte/remediere-conversie-eyeglasses24', permanent: true },
      { source: '/ro/projects/:path*', destination: '/proiecte', permanent: true },

      // Blog vechi → homepage
      { source: '/category/:path*', destination: '/', permanent: true },
      { source: '/insights', destination: '/', permanent: true },
      { source: '/insights/', destination: '/', permanent: true },
      { source: '/digital-trends', destination: '/', permanent: true },
      { source: '/digital-trends/', destination: '/', permanent: true },
      { source: '/:path*/blog/:slug*', destination: '/', permanent: true },

      // Servicii RO (primul set)
      { source: '/google-ro', destination: '/reclame-platite/google-ads', permanent: true },
      { source: '/facebook-ro', destination: '/reclame-platite/facebook-ads', permanent: true },
      { source: '/instagram-ro', destination: '/reclame-platite/instagram-ads', permanent: true },
      { source: '/tiktok-ro', destination: '/reclame-platite/tiktok-ads', permanent: true },
      { source: '/linkedin-ro', destination: '/reclame-platite/linkedin-ads', permanent: true },
      { source: '/site-de-lead-generation', destination: '/webdesign/website-lead-generation', permanent: true },
      { source: '/website-companie', destination: '/webdesign/website-companie', permanent: true },
      { source: '/magazine-e-commerce', destination: '/webdesign/magazine-online', permanent: true },
      { source: '/mentenanta-website-ro', destination: '/webdesign/mentenanta-website', permanent: true },
      { source: '/strategie-digitala-ro', destination: '/marketing-digital/strategie-digitala', permanent: true },
      { source: '/solutii-email-marketing-ro', destination: '/marketing-digital/email-marketing', permanent: true },
      { source: '/solutii-crm-ro', destination: '/marketing-digital/strategie-digitala', permanent: true },
      { source: '/solutii-cro', destination: '/marketing-digital/cro', permanent: true },
      { source: '/solutii-social-media-marketing-ro', destination: '/marketing-digital/social-media', permanent: true },
      { source: '/despre-noi', destination: '/despre-nesco-digital', permanent: true },
      { source: '/despre-noi/', destination: '/despre-nesco-digital', permanent: true },
      { source: '/hai-sa-vorbim', destination: '/contact', permanent: true },
      { source: '/google-ro/', destination: '/reclame-platite/google-ads', permanent: true },
      { source: '/facebook-ro/', destination: '/reclame-platite/facebook-ads', permanent: true },
      { source: '/hai-sa-vorbim/', destination: '/contact', permanent: true },

      // EN old URLs
      { source: '/en/google-ads', destination: '/en/paid-ads/google-ads', permanent: true },
      { source: '/en/facebook-ads', destination: '/en/paid-ads/facebook-ads', permanent: true },
      { source: '/en/about-nesco-digital', destination: '/en/about', permanent: true },
      { source: '/en/projects', destination: '/en/projects', permanent: true },
    ];
  },
  async headers() {
    return [
      {
        source: "/(.*)",
        headers: [
          { key: "X-Content-Type-Options", value: "nosniff" },
          { key: "X-Frame-Options", value: "DENY" },
          { key: "X-XSS-Protection", value: "1; mode=block" },
          { key: "Referrer-Policy", value: "strict-origin-when-cross-origin" },
        ],
      },
    ];
  },
  // Preserve exact URL structure from existing site
  trailingSlash: true,
};

export default nextConfig;
