import type { Locale } from "./translations";

export type ProjectCategory = "B2B" | "E-commerce" | "SaaS" | "DTC" | "Sănătate" | "Performance Marketing" | "Online Education" | "Growth Sprint" | "Webdesign";

export interface ProjectMetric {
  value: string;
  label: string;
}

export interface ProjectI18n {
  title: string;
  shortTitle: string;
  metricMain: string;
  metricSub: string;
  industry: string;
  description: string;
  challenge: string;
  solution: string;
  metrics: ProjectMetric[];
  timeline: string;
  metaTitle: string;
  metaDescription: string;
}

export interface Project {
  slug: string;
  categories: ProjectCategory[];
  tags: string[];
  services: string[];
  heroImage?: string;
  accentColor: string;
  accentText: string;
  featured: boolean;
  clientUrl?: string;
  i18n: { ro: ProjectI18n; en: ProjectI18n; de: ProjectI18n };
}

export function getLocalizedProject(project: Project, locale: Locale): Project & ProjectI18n {
  return { ...project, ...project.i18n[locale] };
}

export const projects: Project[] = [
  {
    slug: "venituri-de-7-cifre-b2b-seo-performance-marketing-in-10-luni",
    categories: ["B2B", "Performance Marketing"],
    tags: ["B2B", "SEO", "Google Ads", "LinkedIn Ads", "Email Marketing"],
    services: ["Google Ads", "Facebook Ads", "Instagram Ads", "LinkedIn Ads", "SEO", "Email Marketing", "CRO"],
    heroImage: "/proiecte/venituri-de-7-cifre-b2b-seo-performance-marketing-in-10-luni/hero.png",
    accentColor: "rgba(96,165,250,0.1)",
    accentText: "#60a5fa",
    featured: true,
    i18n: {
      ro: {
        title: "Venituri de 7 Cifre – B2B SEO & Performance Marketing în 10 luni",
        shortTitle: "B2B SEO & Performance Marketing",
        metricMain: "7 Cifre",
        metricSub: "Revenue în 10 luni",
        industry: "B2B",
        description: "Strategie full-funnel SEO + performance marketing pentru o companie B2B de nișă care dorea să atingă venituri de 7 cifre prin canale digitale.",
        challenge: "Compania se confrunta cu trafic organic scăzut și rate de retenție reduse, necesitând vizibilitate online îmbunătățită și creștere accelerată a vânzărilor.",
        solution: "Am implementat o strategie combinată de SEO strategic cu cuvinte cheie cu intenție ridicată, campanii PPC pe Google și canale sociale pentru trafic imediat, testare A/B sistematică și programe de loialitate prin email marketing pentru achiziții repetate.",
        metrics: [
          { value: "7 cifre", label: "Revenue în 10 luni" },
          { value: "Top 1-3", label: "Clasamente Google pentru 20+ keywords" },
          { value: "+40%", label: "Creștere retenție clienți" },
          { value: "10 luni", label: "Durată proiect" },
        ],
        timeline: "10 luni",
        metaTitle: "Venituri de 7 Cifre – B2B SEO & Performance Marketing | Nesco Digital",
        metaDescription: "Cum am ajutat o companie B2B să atingă venituri de 7 cifre în 10 luni prin SEO strategic și performance marketing omnichannel.",
      },
      en: {
        title: "7-Figure Revenue – B2B SEO & Performance Marketing in 10 months",
        shortTitle: "B2B SEO & Performance Marketing",
        metricMain: "7 Figures",
        metricSub: "Revenue in 10 months",
        industry: "B2B",
        description: "Full-funnel SEO + performance marketing strategy for a niche B2B company aiming to reach 7-figure revenue through digital channels.",
        challenge: "The company faced low organic traffic and reduced retention rates, requiring improved online visibility and accelerated sales growth.",
        solution: "We implemented a combined strategy of strategic SEO with high-intent keywords, PPC campaigns on Google and social channels for immediate traffic, systematic A/B testing, and loyalty programs through email marketing for repeat purchases.",
        metrics: [
          { value: "7 Figures", label: "Revenue in 10 months" },
          { value: "Top 1-3", label: "Google rankings for 20+ keywords" },
          { value: "+40%", label: "Customer retention growth" },
          { value: "10 months", label: "Project duration" },
        ],
        timeline: "10 months",
        metaTitle: "7-Figure Revenue – B2B SEO & Performance Marketing | Nesco Digital",
        metaDescription: "How we helped a B2B company reach 7-figure revenue in 10 months through strategic SEO and omnichannel performance marketing.",
      },
      de: {
        title: "7-stelliger Umsatz – B2B SEO & Performance Marketing in 10 Monaten",
        shortTitle: "B2B SEO & Performance Marketing",
        metricMain: "7-stellig",
        metricSub: "Umsatz in 10 Monaten",
        industry: "B2B",
        description: "Full-Funnel-SEO + Performance-Marketing-Strategie für ein Nischen-B2B-Unternehmen mit dem Ziel, 7-stellige Umsätze über digitale Kanäle zu erzielen.",
        challenge: "Das Unternehmen hatte niedrigen organischen Traffic und geringe Retentionsraten und benötigte verbesserte Online-Sichtbarkeit sowie beschleunigtes Umsatzwachstum.",
        solution: "Wir implementierten eine kombinierte Strategie aus strategischem SEO mit High-Intent-Keywords, PPC-Kampagnen auf Google und sozialen Kanälen für sofortigen Traffic, systematisches A/B-Testing und Kundenbindungsprogramme durch E-Mail-Marketing.",
        metrics: [
          { value: "7-stellig", label: "Umsatz in 10 Monaten" },
          { value: "Top 1-3", label: "Google-Rankings für 20+ Keywords" },
          { value: "+40%", label: "Steigerung der Kundenbindung" },
          { value: "10 Monate", label: "Projektdauer" },
        ],
        timeline: "10 Monate",
        metaTitle: "7-stelliger Umsatz – B2B SEO & Performance Marketing | Nesco Digital",
        metaDescription: "Wie wir einem B2B-Unternehmen geholfen haben, in 10 Monaten 7-stellige Umsätze durch strategisches SEO und Omnichannel-Performance-Marketing zu erzielen.",
      },
    },
  },
  {
    slug: "crestere-de-400-brand-e-commerce-12-luni",
    categories: ["E-commerce", "Performance Marketing"],
    tags: ["E-commerce", "Facebook Ads", "Google Ads", "CRO", "Email Marketing"],
    services: ["Google Ads", "Facebook Ads", "Instagram Ads", "TikTok Ads", "CRO"],
    heroImage: "/proiecte/crestere-de-400-brand-e-commerce-12-luni/hero.png",
    accentColor: "rgba(86,219,132,0.1)",
    accentText: "#56db84",
    featured: true,
    i18n: {
      ro: {
        title: "Creștere de 400% – Scalare Brand E-Commerce în 12 luni",
        shortTitle: "Scalare Brand E-Commerce",
        metricMain: "400%",
        metricSub: "Creștere revenue în 12 luni",
        industry: "E-commerce",
        description: "Optimizare funnel de vânzări combinată cu storytelling vizual pentru o experiență de cumpărare fluidă și emoțional captivantă — rezultat: 400% creștere revenue.",
        challenge: "Brand-ul se confrunta cu rate de conversie scăzute și creștere stagnantă, necesitând o intervenție profundă pe traseul de cumpărare și accelerarea veniturilor.",
        solution: "Analiză de piață profundă, optimizarea funnel-ului (checkout simplificat, reducerea punctelor de fricțiune), strategii de upsell și bundling pentru creșterea AOV, și refresh creativ axat pe storytelling emoțional.",
        metrics: [
          { value: "400%", label: "Creștere revenue în 12 luni" },
          { value: "+30%", label: "Creștere AOV (Average Order Value)" },
          { value: "+28%", label: "Îmbunătățire rată de conversie" },
          { value: "12 luni", label: "Durată proiect" },
        ],
        timeline: "12 luni",
        metaTitle: "Creștere de 400% – Scalare Brand E-Commerce | Nesco Digital",
        metaDescription: "Cum am scalat un brand de e-commerce cu 400% în 12 luni prin optimizarea funnel-ului, creative storytelling și performance marketing omnichannel.",
      },
      en: {
        title: "400% Growth – E-Commerce Brand Scaling in 12 months",
        shortTitle: "E-Commerce Brand Scaling",
        metricMain: "400%",
        metricSub: "Revenue growth in 12 months",
        industry: "E-commerce",
        description: "Sales funnel optimization combined with visual storytelling for a smooth and emotionally engaging buying experience — result: 400% revenue growth.",
        challenge: "The brand faced low conversion rates and stagnant growth, requiring deep intervention in the purchase journey and revenue acceleration.",
        solution: "In-depth market analysis, funnel optimization (simplified checkout, friction reduction), upsell and bundling strategies to increase AOV, and emotional storytelling-focused creative refresh.",
        metrics: [
          { value: "400%", label: "Revenue growth in 12 months" },
          { value: "+30%", label: "AOV growth (Average Order Value)" },
          { value: "+28%", label: "Conversion rate improvement" },
          { value: "12 months", label: "Project duration" },
        ],
        timeline: "12 months",
        metaTitle: "400% Growth – E-Commerce Brand Scaling | Nesco Digital",
        metaDescription: "How we scaled an e-commerce brand by 400% in 12 months through funnel optimization, creative storytelling and omnichannel performance marketing.",
      },
      de: {
        title: "400% Wachstum – E-Commerce-Marken-Skalierung in 12 Monaten",
        shortTitle: "E-Commerce-Marken-Skalierung",
        metricMain: "400%",
        metricSub: "Umsatzwachstum in 12 Monaten",
        industry: "E-Commerce",
        description: "Verkaufstrichter-Optimierung kombiniert mit visuellem Storytelling für ein reibungsloses und emotional ansprechendes Kauferlebnis — Ergebnis: 400% Umsatzwachstum.",
        challenge: "Die Marke hatte niedrige Konversionsraten und stagnierendes Wachstum und benötigte eine tiefgreifende Intervention im Kaufprozess und Umsatzbeschleunigung.",
        solution: "Tiefgehende Marktanalyse, Funnel-Optimierung (vereinfachter Checkout, Reduzierung von Reibungspunkten), Upsell- und Bundling-Strategien zur AOV-Steigerung und kreatives Refresh mit Fokus auf emotionales Storytelling.",
        metrics: [
          { value: "400%", label: "Umsatzwachstum in 12 Monaten" },
          { value: "+30%", label: "AOV-Steigerung (Average Order Value)" },
          { value: "+28%", label: "Verbesserung der Konversionsrate" },
          { value: "12 Monate", label: "Projektdauer" },
        ],
        timeline: "12 Monate",
        metaTitle: "400% Wachstum – E-Commerce-Marken-Skalierung | Nesco Digital",
        metaDescription: "Wie wir eine E-Commerce-Marke in 12 Monaten um 400% skaliert haben durch Funnel-Optimierung, Creative Storytelling und Omnichannel-Performance-Marketing.",
      },
    },
  },
  {
    slug: "roi-de-5x-extinderea-platforme-saas-9-luni",
    categories: ["SaaS", "B2B"],
    tags: ["SaaS", "LinkedIn Ads", "Google Ads", "B2B"],
    services: ["LinkedIn Ads", "Google Ads", "Facebook Ads", "Instagram Ads", "TikTok Ads"],
    heroImage: "/proiecte/roi-de-5x-extinderea-platforme-saas-9-luni/hero.png",
    accentColor: "rgba(167,139,250,0.1)",
    accentText: "#a78bfa",
    featured: true,
    i18n: {
      ro: {
        title: "ROI de 5X – Extinderea unei Platforme SaaS în 9 luni",
        shortTitle: "Expansiune Platformă SaaS",
        metricMain: "5× ROI",
        metricSub: "în 9 luni",
        industry: "SaaS",
        description: "LinkedIn Ads + Google Ads targetând factorii de decizie enterprise, cu audit complet de campanii și realocarea bugetelor spre canalele cu cel mai mare potențial.",
        challenge: "Platforma SaaS necesita o expansiune rapidă a bazei de utilizatori, cu îmbunătățirea ROI-ului de marketing fără creșterea proporțională a costurilor de achiziție clienți.",
        solution: "Audit campanii și realocarea bugetelor spre canale high-performing, segmentare avansată a audienței pe baza demografiei și comportamentului, testare creativă iterativă și retargeting avansat cu reclame dinamice.",
        metrics: [
          { value: "5× ROI", label: "Return on Investment" },
          { value: "+10.000", label: "Lead-uri generate" },
          { value: "+70%", label: "Creștere engagement utilizatori" },
          { value: "9 luni", label: "Durată proiect" },
        ],
        timeline: "9 luni",
        metaTitle: "ROI de 5X – Extinderea unei Platforme SaaS | Nesco Digital",
        metaDescription: "Cum am ajutat o platformă SaaS să obțină un ROI de 5X și 10.000+ lead-uri în 9 luni prin LinkedIn Ads și strategie omnichannel B2B.",
      },
      en: {
        title: "5X ROI – SaaS Platform Expansion in 9 months",
        shortTitle: "SaaS Platform Expansion",
        metricMain: "5× ROI",
        metricSub: "in 9 months",
        industry: "SaaS",
        description: "LinkedIn Ads + Google Ads targeting enterprise decision-makers, with full campaign audit and budget reallocation to highest-potential channels.",
        challenge: "The SaaS platform needed rapid user base expansion, improving marketing ROI without a proportional increase in customer acquisition costs.",
        solution: "Campaign audit and budget reallocation to high-performing channels, advanced audience segmentation based on demographics and behavior, iterative creative testing and advanced retargeting with dynamic ads.",
        metrics: [
          { value: "5× ROI", label: "Return on Investment" },
          { value: "+10,000", label: "Leads generated" },
          { value: "+70%", label: "User engagement growth" },
          { value: "9 months", label: "Project duration" },
        ],
        timeline: "9 months",
        metaTitle: "5X ROI – SaaS Platform Expansion | Nesco Digital",
        metaDescription: "How we helped a SaaS platform achieve 5X ROI and 10,000+ leads in 9 months through LinkedIn Ads and B2B omnichannel strategy.",
      },
      de: {
        title: "5X ROI – SaaS-Plattform-Expansion in 9 Monaten",
        shortTitle: "SaaS-Plattform-Expansion",
        metricMain: "5× ROI",
        metricSub: "in 9 Monaten",
        industry: "SaaS",
        description: "LinkedIn Ads + Google Ads targeting Enterprise-Entscheidungsträger, mit vollständigem Kampagnen-Audit und Budgetumverteilung auf Kanäle mit dem größten Potenzial.",
        challenge: "Die SaaS-Plattform benötigte eine schnelle Erweiterung der Nutzerbasis mit verbessertem Marketing-ROI ohne proportionale Erhöhung der Kundenakquisitionskosten.",
        solution: "Kampagnen-Audit und Budgetumverteilung auf High-Performing-Kanäle, erweiterte Zielgruppensegmentierung basierend auf Demografie und Verhalten, iteratives kreatives Testen und erweitertes Retargeting mit dynamischen Anzeigen.",
        metrics: [
          { value: "5× ROI", label: "Return on Investment" },
          { value: "+10.000", label: "Generierte Leads" },
          { value: "+70%", label: "Steigerung des Nutzer-Engagements" },
          { value: "9 Monate", label: "Projektdauer" },
        ],
        timeline: "9 Monate",
        metaTitle: "5X ROI – SaaS-Plattform-Expansion | Nesco Digital",
        metaDescription: "Wie wir einer SaaS-Plattform geholfen haben, in 9 Monaten einen 5X ROI und 10.000+ Leads durch LinkedIn Ads und B2B-Omnichannel-Strategie zu erzielen.",
      },
    },
  },
  {
    slug: "crestere-de-10x-brand-dtc-14-luni",
    categories: ["DTC", "E-commerce"],
    tags: ["DTC", "TikTok Ads", "Instagram Ads", "Facebook Ads", "Email Marketing"],
    services: ["TikTok Ads", "Instagram Ads", "Facebook Ads", "Google Ads", "Email Marketing", "CRO"],
    heroImage: "/proiecte/crestere-de-10x-brand-dtc-14-luni/hero.png",
    accentColor: "rgba(251,146,60,0.1)",
    accentText: "#fb923c",
    featured: true,
    i18n: {
      ro: {
        title: "Creștere de 10x – Brand DTC de la $250K la $2,5M în 14 luni",
        shortTitle: "Creștere Brand DTC",
        metricMain: "10×",
        metricSub: "Revenue în 14 luni",
        industry: "E-commerce",
        description: "TikTok + Instagram + Facebook + email flows pentru un brand consumer DTC — de la $250.000 la $2.500.000 în 14 luni.",
        challenge: "Brand DTC se confrunta cu creștere stagnantă și costuri ridicate de achiziție clienți, necesitând o strategie scalabilă pentru multiplicarea veniturilor.",
        solution: "Campanii A/B intensive pe multiple platforme, redesign complet al funnel-ului de vânzări, implementare analytics pentru monitorizarea comportamentului utilizatorilor, și crearea de materiale creative cu conversie ridicată: reclame video, carusele, landing pages.",
        metrics: [
          { value: "10×", label: "Creștere revenue (de la $250K la $2,5M)" },
          { value: "+35%", label: "Îmbunătățire CTR" },
          { value: "-25%", label: "Reducere CAC (Customer Acquisition Cost)" },
          { value: "14 luni", label: "Durată proiect" },
        ],
        timeline: "14 luni",
        metaTitle: "Creștere de 10x – Brand DTC de la $250K la $2,5M | Nesco Digital",
        metaDescription: "Cum am scalat un brand DTC de 10 ori în 14 luni prin strategie omnichannel TikTok, Instagram, Facebook și email marketing automation.",
      },
      en: {
        title: "10x Growth – DTC Brand from $250K to $2.5M in 14 months",
        shortTitle: "DTC Brand Growth",
        metricMain: "10×",
        metricSub: "Revenue in 14 months",
        industry: "E-commerce",
        description: "TikTok + Instagram + Facebook + email flows for a consumer DTC brand — from $250,000 to $2,500,000 in 14 months.",
        challenge: "The DTC brand faced stagnant growth and high customer acquisition costs, needing a scalable strategy to multiply revenue.",
        solution: "Intensive A/B campaigns across multiple platforms, complete sales funnel redesign, analytics implementation for user behavior monitoring, and creation of high-converting creative materials: video ads, carousels, landing pages.",
        metrics: [
          { value: "10×", label: "Revenue growth ($250K to $2.5M)" },
          { value: "+35%", label: "CTR improvement" },
          { value: "-25%", label: "CAC reduction (Customer Acquisition Cost)" },
          { value: "14 months", label: "Project duration" },
        ],
        timeline: "14 months",
        metaTitle: "10x Growth – DTC Brand from $250K to $2.5M | Nesco Digital",
        metaDescription: "How we scaled a DTC brand 10x in 14 months through omnichannel TikTok, Instagram, Facebook and email marketing automation strategy.",
      },
      de: {
        title: "10x Wachstum – DTC-Marke von $250K auf $2,5M in 14 Monaten",
        shortTitle: "DTC-Marken-Wachstum",
        metricMain: "10×",
        metricSub: "Umsatz in 14 Monaten",
        industry: "E-Commerce",
        description: "TikTok + Instagram + Facebook + E-Mail-Flows für eine Consumer-DTC-Marke — von $250.000 auf $2.500.000 in 14 Monaten.",
        challenge: "Die DTC-Marke hatte stagnierendes Wachstum und hohe Kundenakquisitionskosten und benötigte eine skalierbare Strategie zur Umsatzmultiplikation.",
        solution: "Intensive A/B-Kampagnen auf mehreren Plattformen, komplettes Redesign des Verkaufstrichters, Analytics-Implementierung zur Nutzerverhalten-Überwachung und Erstellung von High-Converting-Creatives: Videoanzeigen, Karussells, Landing Pages.",
        metrics: [
          { value: "10×", label: "Umsatzwachstum ($250K auf $2,5M)" },
          { value: "+35%", label: "CTR-Verbesserung" },
          { value: "-25%", label: "CAC-Reduzierung (Customer Acquisition Cost)" },
          { value: "14 Monate", label: "Projektdauer" },
        ],
        timeline: "14 Monate",
        metaTitle: "10x Wachstum – DTC-Marke von $250K auf $2,5M | Nesco Digital",
        metaDescription: "Wie wir eine DTC-Marke in 14 Monaten um das 10-fache skaliert haben durch TikTok, Instagram, Facebook und E-Mail-Marketing-Automation.",
      },
    },
  },
  {
    slug: "cresterea-numarului-de-rezervari",
    categories: ["Performance Marketing"],
    tags: ["Hospitality", "Email Marketing", "PPC", "Facebook Ads", "Display Ads"],
    services: ["Digital Strategy", "Email Marketing", "PPC Management", "Facebook Ads", "YouTube Ads", "Display Advertising", "Remarketing"],
    heroImage: "/proiecte/cresterea-numarului-de-rezervari/hero.jpg",
    accentColor: "rgba(251,191,36,0.1)",
    accentText: "#fbbf24",
    featured: false,
    i18n: {
      ro: {
        title: "Creșterea Numărului de Rezervări – Accor Hotels (Ibis, Pullman, Sofitel)",
        shortTitle: "Creștere Rezervări Accor Hotels",
        metricMain: "3×",
        metricSub: "Creștere rezervări",
        industry: "Hospitality",
        description: "Strategie multi-canal pentru Accor Hotels (Ibis, Pullman, Sofitel) în UK, Irlanda, Franța, Spania și Portugalia — creștere de 3× a rezervărilor și reducere cu 27% a costului per rezervare.",
        challenge: "Clienții comparau ofertele pe aproximativ 15 website-uri diferite înainte de a finaliza o rezervare, generând costuri ridicate de achiziție și rate mari de abandon al procesului de booking.",
        solution: "Strategie digitală omnichannel cu campanii PPC, email marketing cu automatizări și fluxuri de retargeting prin email pentru recuperarea rezervărilor abandonate, targetând simultan brandurile Ibis, Pullman și Sofitel în 5 piețe europene.",
        metrics: [
          { value: "3×", label: "Creștere rezervări" },
          { value: "-27%", label: "Cost per rezervare" },
          { value: "58%", label: "Email open rate" },
        ],
        timeline: "—",
        metaTitle: "3× Creștere Rezervări – Accor Hotels (Ibis, Pullman, Sofitel) | Nesco Digital",
        metaDescription: "Cum am crescut de 3 ori rezervările pentru Accor Hotels în 5 piețe europene prin strategie PPC, email marketing și remarketing omnichannel.",
      },
      en: {
        title: "3× Booking Growth – Accor Hotels (Ibis, Pullman, Sofitel)",
        shortTitle: "Accor Hotels Booking Growth",
        metricMain: "3×",
        metricSub: "Booking growth",
        industry: "Hospitality",
        description: "Multi-channel strategy for Accor Hotels (Ibis, Pullman, Sofitel) in the UK, Ireland, France, Spain and Portugal — 3× booking growth and 27% reduction in cost per booking.",
        challenge: "Customers compared offers on approximately 15 different websites before completing a booking, generating high acquisition costs and high booking abandonment rates.",
        solution: "Omnichannel digital strategy with PPC campaigns, email marketing with automations and email retargeting flows to recover abandoned bookings, simultaneously targeting Ibis, Pullman and Sofitel brands in 5 European markets.",
        metrics: [
          { value: "3×", label: "Booking growth" },
          { value: "-27%", label: "Cost per booking" },
          { value: "58%", label: "Email open rate" },
        ],
        timeline: "—",
        metaTitle: "3× Booking Growth – Accor Hotels (Ibis, Pullman, Sofitel) | Nesco Digital",
        metaDescription: "How we tripled bookings for Accor Hotels across 5 European markets through PPC, email marketing and omnichannel remarketing.",
      },
      de: {
        title: "3× Buchungswachstum – Accor Hotels (Ibis, Pullman, Sofitel)",
        shortTitle: "Accor Hotels Buchungswachstum",
        metricMain: "3×",
        metricSub: "Buchungswachstum",
        industry: "Hospitality",
        description: "Multi-Kanal-Strategie für Accor Hotels (Ibis, Pullman, Sofitel) in UK, Irland, Frankreich, Spanien und Portugal — 3× Buchungswachstum und 27% Reduzierung der Kosten pro Buchung.",
        challenge: "Kunden verglichen Angebote auf ca. 15 verschiedenen Websites, bevor sie eine Buchung abschlossen, was zu hohen Akquisitionskosten und hohen Buchungsabbruchraten führte.",
        solution: "Omnichannel-Digital-Strategie mit PPC-Kampagnen, E-Mail-Marketing mit Automatisierungen und E-Mail-Retargeting-Flows zur Rückgewinnung abgebrochener Buchungen, gleichzeitig targeting Ibis, Pullman und Sofitel in 5 europäischen Märkten.",
        metrics: [
          { value: "3×", label: "Buchungswachstum" },
          { value: "-27%", label: "Kosten pro Buchung" },
          { value: "58%", label: "E-Mail-Öffnungsrate" },
        ],
        timeline: "—",
        metaTitle: "3× Buchungswachstum – Accor Hotels (Ibis, Pullman, Sofitel) | Nesco Digital",
        metaDescription: "Wie wir die Buchungen für Accor Hotels in 5 europäischen Märkten verdreifacht haben durch PPC, E-Mail-Marketing und Omnichannel-Remarketing.",
      },
    },
  },
  {
    slug: "imbunatatirea-calitatii-lead-urilor",
    categories: ["B2B", "Performance Marketing"],
    tags: ["B2B", "Google Ads", "CRO", "PPC", "Lead Generation"],
    services: ["Landing Page Design", "PPC Management", "Google Ads", "Display Advertising", "Remarketing"],
    heroImage: "/proiecte/imbunatatirea-calitatii-lead-urilor/hero.jpg",
    accentColor: "rgba(96,165,250,0.1)",
    accentText: "#60a5fa",
    featured: false,
    i18n: {
      ro: {
        title: "Îmbunătățirea Calității Lead-urilor – Experian",
        shortTitle: "Lead Quality Experian",
        metricMain: "+84%",
        metricSub: "Calitate lead-uri",
        industry: "Financial Services",
        description: "Restructurarea campaniilor Google AdWords pentru Experian — +84% calitate lead-uri, -36% cost per client nou și +9.9% rată de conversie pe landing page.",
        challenge: "Campaniile Google AdWords existente aveau cuvinte cheie duplicate, alocare slabă a bugetului și costuri-per-click umflate, generând lead-uri de calitate scăzută cu mai puțin de 1/3 din rata de conversie așteptată.",
        solution: "Restructurare completă a contului AdWords cu diferențiere clară între utilizatorii cu intenție ridicată și cei cu intenție scăzută, implementare tracking conversii, testare A/B sistematică și optimizare landing page pentru maximizarea calității lead-urilor.",
        metrics: [
          { value: "-36%", label: "Cost per client nou" },
          { value: "+84%", label: "Calitate lead-uri" },
          { value: "+9.9%", label: "Conversie landing page" },
        ],
        timeline: "—",
        metaTitle: "+84% Calitate Lead-uri – Experian | Nesco Digital",
        metaDescription: "Cum am îmbunătățit calitatea lead-urilor Experian cu 84% și am redus costul per client nou cu 36% prin restructurarea campaniilor Google Ads.",
      },
      en: {
        title: "Lead Quality Improvement – Experian",
        shortTitle: "Lead Quality Experian",
        metricMain: "+84%",
        metricSub: "Lead quality",
        industry: "Financial Services",
        description: "Google AdWords campaign restructuring for Experian — +84% lead quality, -36% cost per new client and +9.9% landing page conversion rate.",
        challenge: "Existing Google AdWords campaigns had duplicate keywords, poor budget allocation and inflated cost-per-click, generating low-quality leads with less than 1/3 of the expected conversion rate.",
        solution: "Complete AdWords account restructure with clear differentiation between high-intent and low-intent users, conversion tracking implementation, systematic A/B testing and landing page optimization to maximize lead quality.",
        metrics: [
          { value: "-36%", label: "Cost per new client" },
          { value: "+84%", label: "Lead quality" },
          { value: "+9.9%", label: "Landing page conversion" },
        ],
        timeline: "—",
        metaTitle: "+84% Lead Quality – Experian | Nesco Digital",
        metaDescription: "How we improved Experian's lead quality by 84% and reduced cost per new client by 36% through Google Ads campaign restructuring.",
      },
      de: {
        title: "Verbesserung der Lead-Qualität – Experian",
        shortTitle: "Lead-Qualität Experian",
        metricMain: "+84%",
        metricSub: "Lead-Qualität",
        industry: "Finanzdienstleistungen",
        description: "Restrukturierung der Google AdWords-Kampagnen für Experian — +84% Lead-Qualität, -36% Kosten pro Neukunden und +9,9% Landing-Page-Konversionsrate.",
        challenge: "Bestehende Google AdWords-Kampagnen hatten duplizierte Keywords, schlechte Budgetzuteilung und überhöhte Cost-per-Click, was zu Low-Quality-Leads mit weniger als 1/3 der erwarteten Konversionsrate führte.",
        solution: "Vollständige AdWords-Konto-Restrukturierung mit klarer Differenzierung zwischen High-Intent- und Low-Intent-Nutzern, Conversion-Tracking-Implementierung, systematisches A/B-Testing und Landing-Page-Optimierung.",
        metrics: [
          { value: "-36%", label: "Kosten pro Neukunden" },
          { value: "+84%", label: "Lead-Qualität" },
          { value: "+9,9%", label: "Landing-Page-Konversion" },
        ],
        timeline: "—",
        metaTitle: "+84% Lead-Qualität – Experian | Nesco Digital",
        metaDescription: "Wie wir die Lead-Qualität von Experian um 84% verbessert und die Kosten pro Neukunden um 36% durch Google Ads-Kampagnen-Restrukturierung gesenkt haben.",
      },
    },
  },
  {
    slug: "targetarea-unui-nou-public-tinta",
    categories: ["E-commerce", "Performance Marketing"],
    tags: ["E-commerce", "Programmatic Ads", "Display Advertising", "CRO"],
    services: ["Programmatic Display Advertising", "Google Analytics", "Audience Segmentation", "Creative Services"],
    heroImage: "/proiecte/targetarea-unui-nou-public-tinta/hero.jpg",
    accentColor: "rgba(167,139,250,0.1)",
    accentText: "#a78bfa",
    featured: false,
    i18n: {
      ro: {
        title: "Targetarea unui Nou Public Țintă – Douglas",
        shortTitle: "Nou Public Țintă Douglas",
        metricMain: "+12%",
        metricSub: "Conversie clienți noi",
        industry: "Retail / Beauty",
        description: "Campanie programmatică de display advertising pentru Douglas — identificarea și conversia de noi segmente de clienți cu +8% vânzări noi, +12% conversie și -21% cost per conversie.",
        challenge: "Douglas dorea să extindă vânzările prin atragerea de clienți noi care nu interacționaseră anterior cu website-ul, fără a crește disproporționat costurile de achiziție.",
        solution: "Analizarea datelor comportamentale și de interes ale clienților existenți pentru identificarea profilelor demografice ale potențialilor cumpărători, urmată de o campanie programmatică de display de înaltă precizie targetând audiențe asemănătoare.",
        metrics: [
          { value: "+8%", label: "Vânzări clienți noi" },
          { value: "+12%", label: "Rată conversie clienți noi" },
          { value: "-21%", label: "Cost per conversie" },
        ],
        timeline: "—",
        metaTitle: "+12% Conversie Clienți Noi – Douglas | Nesco Digital",
        metaDescription: "Cum am ajutat Douglas să atingă clienți noi prin programmatic display advertising cu +8% vânzări, +12% conversie și -21% cost per conversie.",
      },
      en: {
        title: "New Target Audience – Douglas",
        shortTitle: "New Target Audience Douglas",
        metricMain: "+12%",
        metricSub: "New customer conversion",
        industry: "Retail / Beauty",
        description: "Programmatic display advertising campaign for Douglas — identification and conversion of new customer segments with +8% new sales, +12% conversion and -21% cost per conversion.",
        challenge: "Douglas wanted to expand sales by attracting new customers who had not previously interacted with the website, without disproportionately increasing acquisition costs.",
        solution: "Analysis of behavioral and interest data from existing customers to identify demographic profiles of potential buyers, followed by a high-precision programmatic display campaign targeting similar audiences.",
        metrics: [
          { value: "+8%", label: "New customer sales" },
          { value: "+12%", label: "New customer conversion rate" },
          { value: "-21%", label: "Cost per conversion" },
        ],
        timeline: "—",
        metaTitle: "+12% New Customer Conversion – Douglas | Nesco Digital",
        metaDescription: "How we helped Douglas reach new customers through programmatic display advertising with +8% sales, +12% conversion and -21% cost per conversion.",
      },
      de: {
        title: "Neue Zielgruppe – Douglas",
        shortTitle: "Neue Zielgruppe Douglas",
        metricMain: "+12%",
        metricSub: "Konversion neuer Kunden",
        industry: "Retail / Beauty",
        description: "Programmatische Display-Advertising-Kampagne für Douglas — Identifizierung und Konversion neuer Kundensegmente mit +8% Neuumsatz, +12% Konversion und -21% Kosten pro Konversion.",
        challenge: "Douglas wollte den Umsatz durch Gewinnung neuer Kunden steigern, die zuvor nicht mit der Website interagiert hatten, ohne die Akquisitionskosten unverhältnismäßig zu erhöhen.",
        solution: "Analyse von Verhaltens- und Interessendaten bestehender Kunden zur Identifizierung demografischer Profile potenzieller Käufer, gefolgt von einer hochpräzisen programmatischen Display-Kampagne für ähnliche Zielgruppen.",
        metrics: [
          { value: "+8%", label: "Neukundenumsatz" },
          { value: "+12%", label: "Neukunden-Konversionsrate" },
          { value: "-21%", label: "Kosten pro Konversion" },
        ],
        timeline: "—",
        metaTitle: "+12% Neukunden-Konversion – Douglas | Nesco Digital",
        metaDescription: "Wie wir Douglas geholfen haben, neue Kunden durch programmatisches Display Advertising zu erreichen mit +8% Umsatz, +12% Konversion und -21% Kosten pro Konversion.",
      },
    },
  },
  {
    slug: "remediere-probleme-de-conversie",
    categories: ["E-commerce", "Performance Marketing"],
    tags: ["E-commerce", "CRO", "PPC", "Landing Page", "Lead Generation"],
    services: ["Landing Page Design", "New Funnel Design", "PPC Management", "Display Advertising", "Remarketing"],
    heroImage: "/proiecte/remediere-probleme-de-conversie/hero.jpg",
    accentColor: "rgba(34,211,238,0.1)",
    accentText: "#22d3ee",
    featured: false,
    i18n: {
      ro: {
        title: "Remediere Probleme de Conversie – Eyeglasses24",
        shortTitle: "CRO & Conversii Eyeglasses24",
        metricMain: "-49%",
        metricSub: "Cost per conversie",
        industry: "Retail / eCommerce",
        description: "Redesign landing page și optimizare campanii pentru Eyeglasses24 — reducere cu 49% a costului per conversie și creștere cu 46% a lead-urilor generate în câteva luni.",
        challenge: "Website-ul depășit bloca experiența utilizatorilor și rata de conversie, iar calitatea lead-urilor era critică — mai puțin de o treime din pachetele trimise s-au convertit în clienți activi.",
        solution: "Metodologie agilă pentru crearea unui nou landing page simplificat și elegant care a generat îmbunătățiri semnificative deja din prima lună. Tot traficul plătit a fost redirecționat spre acesta timp de 8 luni, cu optimizare continuă a campaniilor.",
        metrics: [
          { value: "-49%", label: "Cost per conversie" },
          { value: "+46%", label: "Lead-uri generate" },
          { value: "-12%", label: "Cost per click" },
          { value: "+15%", label: "Rată conversie (luna 1)" },
        ],
        timeline: "8 luni",
        metaTitle: "-49% Cost per Conversie – Eyeglasses24 | Nesco Digital",
        metaDescription: "Cum am redus costul per conversie al Eyeglasses24 cu 49% și am crescut lead-urile cu 46% prin redesign landing page și optimizare campanii PPC.",
      },
      en: {
        title: "Conversion Fix – Eyeglasses24",
        shortTitle: "CRO & Conversions Eyeglasses24",
        metricMain: "-49%",
        metricSub: "Cost per conversion",
        industry: "Retail / eCommerce",
        description: "Landing page redesign and campaign optimization for Eyeglasses24 — 49% reduction in cost per conversion and 46% increase in leads generated within months.",
        challenge: "The outdated website blocked user experience and conversion rate, and lead quality was critical — less than a third of sent packages converted into active customers.",
        solution: "Agile methodology for creating a new simplified and elegant landing page that generated significant improvements from the first month. All paid traffic was redirected to it for 8 months, with continuous campaign optimization.",
        metrics: [
          { value: "-49%", label: "Cost per conversion" },
          { value: "+46%", label: "Leads generated" },
          { value: "-12%", label: "Cost per click" },
          { value: "+15%", label: "Conversion rate (month 1)" },
        ],
        timeline: "8 months",
        metaTitle: "-49% Cost per Conversion – Eyeglasses24 | Nesco Digital",
        metaDescription: "How we reduced Eyeglasses24's cost per conversion by 49% and increased leads by 46% through landing page redesign and PPC campaign optimization.",
      },
      de: {
        title: "Konversionsprobleme lösen – Eyeglasses24",
        shortTitle: "CRO & Konversionen Eyeglasses24",
        metricMain: "-49%",
        metricSub: "Kosten pro Konversion",
        industry: "Retail / eCommerce",
        description: "Landing-Page-Redesign und Kampagnen-Optimierung für Eyeglasses24 — 49% Reduzierung der Kosten pro Konversion und 46% Steigerung der generierten Leads innerhalb weniger Monate.",
        challenge: "Die veraltete Website blockierte die Nutzererfahrung und Konversionsrate, und die Lead-Qualität war kritisch — weniger als ein Drittel der versendeten Pakete konvertierten zu aktiven Kunden.",
        solution: "Agile Methodik für die Erstellung einer neuen, vereinfachten und eleganten Landing Page, die bereits ab dem ersten Monat signifikante Verbesserungen generierte. Der gesamte bezahlte Traffic wurde 8 Monate lang dorthin umgeleitet.",
        metrics: [
          { value: "-49%", label: "Kosten pro Konversion" },
          { value: "+46%", label: "Generierte Leads" },
          { value: "-12%", label: "Cost per Click" },
          { value: "+15%", label: "Konversionsrate (Monat 1)" },
        ],
        timeline: "8 Monate",
        metaTitle: "-49% Kosten pro Konversion – Eyeglasses24 | Nesco Digital",
        metaDescription: "Wie wir die Kosten pro Konversion von Eyeglasses24 um 49% gesenkt und Leads um 46% durch Landing-Page-Redesign und PPC-Kampagnen-Optimierung gesteigert haben.",
      },
    },
  },
  {
    slug: "crestere-google-ads-e-commerce",
    categories: ["E-commerce", "Performance Marketing"],
    tags: ["E-commerce", "Google Ads", "CRO", "Performance Max"],
    services: ["Google Ads", "CRO", "Performance Max", "Shopping Ads"],
    heroImage: "/proiecte/crestere-google-ads-e-commerce/hero.jpg",
    accentColor: "rgba(244,114,182,0.1)",
    accentText: "#f472b6",
    featured: false,
    i18n: {
      ro: {
        title: "+200% Vânzări – Scalare Google Ads E-Commerce",
        shortTitle: "Scalare Google Ads E-Commerce",
        metricMain: "+200%",
        metricSub: "Vânzări în 6 luni",
        industry: "E-commerce",
        description: "Performance Max + Shopping Ads cu smart bidding ROAS-optimizat pentru un brand de e-commerce — 200% creștere vânzări în 6 luni.",
        challenge: "Campaniile Google Ads existente nu generau rezultatele dorite — ROAS sub target și costuri ridicate de achiziție.",
        solution: "Restructurare completă a campaniilor Google Ads cu Performance Max și Shopping Ads, implementare smart bidding cu target ROAS optimizat, și optimizare continuă bazată pe date.",
        metrics: [
          { value: "+200%", label: "Creștere vânzări în 6 luni" },
          { value: "5× ROAS", label: "Return on Ad Spend" },
          { value: "-38%", label: "Reducere CPA față de media industriei" },
          { value: "6 luni", label: "Durată proiect" },
        ],
        timeline: "6 luni",
        metaTitle: "+200% Vânzări – Scalare Google Ads E-Commerce | Nesco Digital",
        metaDescription: "Cum am crescut vânzările unui brand de e-commerce cu 200% în 6 luni prin Performance Max și Shopping Ads cu smart bidding ROAS-optimizat.",
      },
      en: {
        title: "+200% Sales – Google Ads E-Commerce Scaling",
        shortTitle: "Google Ads E-Commerce Scaling",
        metricMain: "+200%",
        metricSub: "Sales in 6 months",
        industry: "E-commerce",
        description: "Performance Max + Shopping Ads with ROAS-optimized smart bidding for an e-commerce brand — 200% sales growth in 6 months.",
        challenge: "Existing Google Ads campaigns were not generating desired results — below-target ROAS and high acquisition costs.",
        solution: "Complete Google Ads campaign restructure with Performance Max and Shopping Ads, smart bidding implementation with optimized target ROAS, and continuous data-driven optimization.",
        metrics: [
          { value: "+200%", label: "Sales growth in 6 months" },
          { value: "5× ROAS", label: "Return on Ad Spend" },
          { value: "-38%", label: "CPA reduction vs. industry average" },
          { value: "6 months", label: "Project duration" },
        ],
        timeline: "6 months",
        metaTitle: "+200% Sales – Google Ads E-Commerce Scaling | Nesco Digital",
        metaDescription: "How we grew an e-commerce brand's sales by 200% in 6 months through Performance Max and Shopping Ads with ROAS-optimized smart bidding.",
      },
      de: {
        title: "+200% Umsatz – Google Ads E-Commerce-Skalierung",
        shortTitle: "Google Ads E-Commerce-Skalierung",
        metricMain: "+200%",
        metricSub: "Umsatz in 6 Monaten",
        industry: "E-Commerce",
        description: "Performance Max + Shopping Ads mit ROAS-optimiertem Smart Bidding für eine E-Commerce-Marke — 200% Umsatzwachstum in 6 Monaten.",
        challenge: "Bestehende Google Ads-Kampagnen erzielten nicht die gewünschten Ergebnisse — ROAS unter Target und hohe Akquisitionskosten.",
        solution: "Vollständige Restrukturierung der Google Ads-Kampagnen mit Performance Max und Shopping Ads, Smart-Bidding-Implementierung mit optimiertem Ziel-ROAS und kontinuierliche datengestützte Optimierung.",
        metrics: [
          { value: "+200%", label: "Umsatzwachstum in 6 Monaten" },
          { value: "5× ROAS", label: "Return on Ad Spend" },
          { value: "-38%", label: "CPA-Reduzierung ggü. Branchendurchschnitt" },
          { value: "6 Monate", label: "Projektdauer" },
        ],
        timeline: "6 Monate",
        metaTitle: "+200% Umsatz – Google Ads E-Commerce-Skalierung | Nesco Digital",
        metaDescription: "Wie wir den Umsatz einer E-Commerce-Marke in 6 Monaten um 200% durch Performance Max und Shopping Ads mit ROAS-optimiertem Smart Bidding gesteigert haben.",
      },
    },
  },
  {
    slug: "clinica-dentara-germania",
    categories: ["Sănătate", "Performance Marketing"],
    tags: ["Sănătate", "Google Ads", "SEO Local", "Lead Generation"],
    services: ["Google Ads", "SEO Local", "CRO", "Landing Page Optimization"],
    heroImage: "/proiecte/clinica-dentara-germania/hero.jpg",
    accentColor: "rgba(34,211,238,0.1)",
    accentText: "#22d3ee",
    featured: false,
    i18n: {
      ro: {
        title: "+50% Programări – Clinică Dentară München",
        shortTitle: "Clinică Dentară Germania",
        metricMain: "+50%",
        metricSub: "Programări pacienți în 6 luni",
        industry: "Sănătate",
        description: "Google Ads local + optimizare landing page pentru cabinet dentar din München — creștere cu 50% a programărilor în 6 luni.",
        challenge: "Cabinetul dentar din München dorea să atragă mai mulți pacienți noi prin canale digitale, cu un buget limitat.",
        solution: "Campanii Google Ads locale targetate geographic, optimizare completă a landing page-urilor pentru conversii maxime, și strategie SEO local pentru a domina căutările relevante.",
        metrics: [
          { value: "+50%", label: "Creștere programări pacienți" },
          { value: "-35%", label: "Reducere cost per lead" },
          { value: "Top 3", label: "Clasamente SEO local München" },
          { value: "6 luni", label: "Durată proiect" },
        ],
        timeline: "6 luni",
        metaTitle: "+50% Programări – Clinică Dentară München | Nesco Digital",
        metaDescription: "Cum am crescut programările unui cabinet dentar din München cu 50% în 6 luni prin Google Ads local și optimizare landing page.",
      },
      en: {
        title: "+50% Appointments – Dental Clinic München",
        shortTitle: "Dental Clinic Germany",
        metricMain: "+50%",
        metricSub: "Patient appointments in 6 months",
        industry: "Healthcare",
        description: "Local Google Ads + landing page optimization for a dental practice in Munich — 50% increase in appointments in 6 months.",
        challenge: "The dental practice in Munich wanted to attract more new patients through digital channels, with a limited budget.",
        solution: "Geographically targeted local Google Ads campaigns, complete landing page optimization for maximum conversions, and local SEO strategy to dominate relevant searches.",
        metrics: [
          { value: "+50%", label: "Patient appointment growth" },
          { value: "-35%", label: "Cost per lead reduction" },
          { value: "Top 3", label: "Local SEO rankings Munich" },
          { value: "6 months", label: "Project duration" },
        ],
        timeline: "6 months",
        metaTitle: "+50% Appointments – Dental Clinic München | Nesco Digital",
        metaDescription: "How we increased a Munich dental clinic's appointments by 50% in 6 months through local Google Ads and landing page optimization.",
      },
      de: {
        title: "+50% Termine – Zahnarztpraxis München",
        shortTitle: "Zahnarztpraxis Deutschland",
        metricMain: "+50%",
        metricSub: "Patiententermine in 6 Monaten",
        industry: "Gesundheit",
        description: "Lokale Google Ads + Landing-Page-Optimierung für eine Zahnarztpraxis in München — 50% mehr Termine in 6 Monaten.",
        challenge: "Die Zahnarztpraxis in München wollte mehr neue Patienten über digitale Kanäle gewinnen, mit begrenztem Budget.",
        solution: "Geografisch ausgerichtete lokale Google Ads-Kampagnen, vollständige Landing-Page-Optimierung für maximale Konversionen und lokale SEO-Strategie zur Dominanz relevanter Suchanfragen.",
        metrics: [
          { value: "+50%", label: "Steigerung der Patiententermine" },
          { value: "-35%", label: "Reduzierung Cost per Lead" },
          { value: "Top 3", label: "Lokale SEO-Rankings München" },
          { value: "6 Monate", label: "Projektdauer" },
        ],
        timeline: "6 Monate",
        metaTitle: "+50% Termine – Zahnarztpraxis München | Nesco Digital",
        metaDescription: "Wie wir die Termine einer Zahnarztpraxis in München in 6 Monaten um 50% durch lokale Google Ads und Landing-Page-Optimierung gesteigert haben.",
      },
    },
  },
  {
    slug: "crestere-8x-venituri-educatie-online",
    categories: ["Online Education", "Growth Sprint"],
    tags: ["Online Education", "Growth Sprint", "Meta Ads", "Google Ads", "TikTok Ads", "Email Marketing"],
    services: ["Meta Ads", "Google Ads", "TikTok Ads", "Email Marketing", "SMS Marketing", "Funnel Design", "Landing Pages", "Video Editing", "Graphic Design"],
    heroImage: undefined,
    accentColor: "rgba(34,197,94,0.1)",
    accentText: "#22c55e",
    featured: false,
    i18n: {
      ro: {
        title: "Creștere de 8× în venituri într-un singur trimestru",
        shortTitle: "8× Venituri în 90 de zile",
        metricMain: "8×",
        metricSub: "creștere venituri",
        industry: "Educație Online",
        description: "De la o platformă stagnantă la un sistem complet de vânzare automată — webinarii, funneluri și campanii care au generat peste 1.000 de lead-uri per eveniment.",
        challenge: "Platforma exista, audiența exista, dar infrastructura de vânzare nu putea susține creșterea. Webinariile nu convertau, funnelurile lipseau, iar campaniile erau fragmentate fără o strategie unitară.",
        solution: "Am reconstruit complet infrastructura de vânzare: landing page-uri dedicate fiecărui webinar, funnel de low-ticket automatizat, campanii integrate pe Google, Meta și TikTok, email și SMS marketing coordonat.",
        metrics: [
          { value: "4.000+", label: "lead-uri generate lunar" },
          { value: "1.000+", label: "lead-uri per webinar" },
          { value: "4–14 lei", label: "cost per lead" },
          { value: "8×", label: "creștere față de luna de start" },
        ],
        timeline: "90 zile",
        metaTitle: "Creștere de 8× Venituri în 90 de zile – Educație Online | Nesco Digital",
        metaDescription: "Cum am crescut de 8 ori veniturile unei platforme de educație online într-un singur trimestru prin funneluri, webinarii și campanii integrate pe Google, Meta și TikTok.",
      },
      en: {
        title: "8× Revenue Growth in a Single Quarter",
        shortTitle: "8× Revenue in 90 Days",
        metricMain: "8×",
        metricSub: "revenue growth",
        industry: "Online Education",
        description: "From a stagnant platform to a complete automated sales system — webinars, funnels and campaigns generating over 1,000 leads per event.",
        challenge: "The platform existed, the audience existed, but the sales infrastructure couldn't support growth. Webinars weren't converting, funnels were missing, campaigns were fragmented.",
        solution: "We rebuilt the entire sales infrastructure: dedicated landing pages for each webinar, automated low-ticket funnel, integrated campaigns across Google, Meta and TikTok, coordinated email and SMS marketing.",
        metrics: [
          { value: "4,000+", label: "leads generated monthly" },
          { value: "1,000+", label: "leads per webinar" },
          { value: "4–14 RON", label: "cost per lead" },
          { value: "8×", label: "growth vs. starting month" },
        ],
        timeline: "90 days",
        metaTitle: "8× Revenue Growth in 90 Days – Online Education | Nesco Digital",
        metaDescription: "How we grew an online education platform's revenue 8x in a single quarter through funnels, webinars and integrated campaigns across Google, Meta and TikTok.",
      },
      de: {
        title: "8-faches Umsatzwachstum in einem Quartal",
        shortTitle: "8× Umsatz in 90 Tagen",
        metricMain: "8×",
        metricSub: "Umsatzwachstum",
        industry: "Online-Bildung",
        description: "Von einer stagnierenden Plattform zu einem vollständigen automatisierten Verkaufssystem — Webinare, Funnels und Kampagnen mit über 1.000 Leads pro Event.",
        challenge: "Die Plattform existierte, das Publikum existierte, aber die Verkaufsinfrastruktur konnte das Wachstum nicht unterstützen. Webinare konvertierten nicht, Funnels fehlten, Kampagnen waren fragmentiert.",
        solution: "Wir haben die gesamte Verkaufsinfrastruktur neu aufgebaut: dedizierte Landing Pages für jedes Webinar, automatisierter Low-Ticket-Funnel, integrierte Kampagnen über Google, Meta und TikTok.",
        metrics: [
          { value: "4.000+", label: "Leads pro Monat generiert" },
          { value: "1.000+", label: "Leads pro Webinar" },
          { value: "4–14 RON", label: "Cost per Lead" },
          { value: "8×", label: "Wachstum vs. Startmonat" },
        ],
        timeline: "90 Tage",
        metaTitle: "8-faches Umsatzwachstum in 90 Tagen – Online-Bildung | Nesco Digital",
        metaDescription: "Wie wir den Umsatz einer Online-Bildungsplattform in einem Quartal um das 8-fache gesteigert haben durch Funnels, Webinare und integrierte Kampagnen über Google, Meta und TikTok.",
      },
    },
  },
  {
    slug: "sistem-vanzare-automat-educatie-online",
    categories: ["Online Education", "Growth Sprint"],
    tags: ["Online Education", "Growth Sprint", "Funnel Design", "Email Marketing", "Subscriptions"],
    services: ["Funnel Design", "Email Marketing", "SMS Marketing", "Platform Development", "Low-ticket Products", "Subscriptions", "Strategie Digitală"],
    heroImage: undefined,
    accentColor: "rgba(86,219,132,0.1)",
    accentText: "#56db84",
    featured: false,
    i18n: {
      ro: {
        title: "De la vânzări manuale la un sistem de revenue automat",
        shortTitle: "Revenue Automatizat",
        metricMain: "+340%",
        metricSub: "creștere venituri",
        industry: "Educație Online",
        description: "Platformă refăcută, funnel de low-ticket, subscriptions și email marketing care vând non-stop fără intervenție umană.",
        challenge: "Vânzările depindeau complet de efortul manual al echipei. Nu exista un sistem care să genereze revenue în mod predictibil și automatizat, iar platforma de cursuri nu susținea experiența așteptată de clienți.",
        solution: "Am refăcut platforma de programe, am construit un funnel de vânzare structurat, am lansat primul produs low-ticket automatizat, am implementat un sistem de subscriptions și am configurat secvențe de email și SMS marketing.",
        metrics: [
          { value: "+340%", label: "creștere venituri lunare" },
          { value: "24/7", label: "vânzări automate fără intervenție" },
          { value: "Low-ticket", label: "primul produs vândut complet automat" },
          { value: "Subscriptions", label: "sistem de retenție implementat" },
        ],
        timeline: "—",
        metaTitle: "+340% Venituri – Sistem de Revenue Automat Educație Online | Nesco Digital",
        metaDescription: "Cum am transformat vânzările manuale ale unei platforme de educație online într-un sistem de revenue automatizat cu +340% creștere lunară.",
      },
      en: {
        title: "From Manual Sales to an Automated Revenue System",
        shortTitle: "Automated Revenue System",
        metricMain: "+340%",
        metricSub: "revenue growth",
        industry: "Online Education",
        description: "Rebuilt platform, low-ticket funnel, subscriptions and email marketing that sell around the clock without human intervention.",
        challenge: "Sales depended entirely on the team's manual effort. There was no system to generate revenue predictably and automatically, and the course platform didn't support the experience clients expected.",
        solution: "We rebuilt the programs platform, constructed a structured sales funnel, launched the first automated low-ticket product, implemented a subscriptions system and configured email and SMS marketing sequences.",
        metrics: [
          { value: "+340%", label: "monthly revenue growth" },
          { value: "24/7", label: "automated sales without intervention" },
          { value: "Low-ticket", label: "first product sold fully automatically" },
          { value: "Subscriptions", label: "retention system implemented" },
        ],
        timeline: "—",
        metaTitle: "+340% Revenue – Automated Revenue System for Online Education | Nesco Digital",
        metaDescription: "How we transformed manual sales of an online education platform into an automated revenue system with +340% monthly growth.",
      },
      de: {
        title: "Von manuellen Verkäufen zu einem automatisierten Umsatzsystem",
        shortTitle: "Automatisiertes Umsatzsystem",
        metricMain: "+340%",
        metricSub: "Umsatzwachstum",
        industry: "Online-Bildung",
        description: "Neu aufgebaute Plattform, Low-Ticket-Funnel, Abonnements und E-Mail-Marketing, die rund um die Uhr ohne menschliches Eingreifen verkaufen.",
        challenge: "Der Umsatz hing vollständig vom manuellen Aufwand des Teams ab. Es gab kein System zur vorhersehbaren und automatisierten Umsatzgenerierung.",
        solution: "Wir haben die Programmplattform neu aufgebaut, einen strukturierten Verkaufsfunnel erstellt, das erste automatisierte Low-Ticket-Produkt gestartet und ein Abonnement-System implementiert.",
        metrics: [
          { value: "+340%", label: "monatliches Umsatzwachstum" },
          { value: "24/7", label: "automatisierter Verkauf ohne Eingriff" },
          { value: "Low-Ticket", label: "erstes vollautomatisch verkauftes Produkt" },
          { value: "Abonnements", label: "Kundenbindungssystem implementiert" },
        ],
        timeline: "—",
        metaTitle: "+340% Umsatz – Automatisiertes Umsatzsystem für Online-Bildung | Nesco Digital",
        metaDescription: "Wie wir manuelle Verkäufe einer Online-Bildungsplattform in ein automatisiertes Umsatzsystem mit +340% monatlichem Wachstum umgewandelt haben.",
      },
    },
  },
  {
    slug: "kada-mobilier-ecommerce",
    categories: ["E-commerce", "Webdesign"],
    tags: ["Webdesign", "E-Commerce"],
    services: ["Webdesign", "Dezvoltare WooCommerce", "UI/UX", "Magazin Online"],
    heroImage: "/proiecte/kada-mobilier-ecommerce/hero.png",
    accentColor: "rgba(201,169,110,0.1)",
    accentText: "#c9a96e",
    featured: false,
    clientUrl: "https://kada.ro",
    i18n: {
      ro: {
        title: "Magazin online de mobilier și decorațiuni premium — Kada.ro",
        shortTitle: "Kada.ro — E-Commerce Mobilier",
        metricMain: "E-Commerce",
        metricSub: "Live",
        industry: "Mobilier & Decorațiuni",
        description: "Magazin live cu sute de produse organizate pe categorii de stil și spațiu, experiență premium de cumpărare, integrare completă plăți și livrare.",
        challenge: "Kada.ro avea nevoie de un magazin online care să reflecte calitatea și estetica produselor premium pe care le comercializează — mobilier și decorațiuni de design, cu o experiență de cumpărare pe măsura brandului.",
        solution: "Dezvoltare magazin WooCommerce cu focus pe experiența vizuală — navigare intuitivă pe categorii de stil și spațiu, prezentare detaliată a produselor, proces de comandă simplificat și design care pune produsele în prim-plan.",
        metrics: [
          { value: "Live", label: "Magazin funcțional cu sute de produse" },
          { value: "WooCommerce", label: "Platformă scalabilă" },
          { value: "100%", label: "Integrare plăți & livrare" },
        ],
        timeline: "—",
        metaTitle: "Kada.ro – Magazin Online Mobilier Premium | Nesco Digital",
        metaDescription: "Dezvoltare magazin WooCommerce pentru Kada.ro — mobilier și decorațiuni premium, cu experiență vizuală premium și integrare completă plăți și livrare.",
      },
      en: {
        title: "Premium furniture and home decor e-commerce store — Kada.ro",
        shortTitle: "Kada.ro — Furniture E-Commerce",
        metricMain: "E-Commerce",
        metricSub: "Live",
        industry: "Furniture & Home Decor",
        description: "Live store with hundreds of products organized by style and space categories, premium shopping experience, full payment and delivery integration.",
        challenge: "Kada.ro needed an online store that reflected the quality and aesthetics of the premium products it sells — designer furniture and decor, with a shopping experience matching the brand.",
        solution: "WooCommerce store development focused on visual experience — intuitive navigation by style and space categories, detailed product presentation, simplified checkout process and design that puts products front and center.",
        metrics: [
          { value: "Live", label: "Functional store with hundreds of products" },
          { value: "WooCommerce", label: "Scalable platform" },
          { value: "100%", label: "Payment & delivery integration" },
        ],
        timeline: "—",
        metaTitle: "Kada.ro – Premium Furniture Online Store | Nesco Digital",
        metaDescription: "WooCommerce store development for Kada.ro — premium furniture and home decor, with a premium visual experience and full payment and delivery integration.",
      },
      de: {
        title: "Premium-Möbel und Heimdeko Online-Shop — Kada.ro",
        shortTitle: "Kada.ro — Möbel E-Commerce",
        metricMain: "E-Commerce",
        metricSub: "Live",
        industry: "Möbel & Heimdekoration",
        description: "Live-Shop mit Hunderten von Produkten nach Stil- und Raumkategorien, Premium-Einkaufserlebnis, vollständige Zahlungs- und Lieferintegration.",
        challenge: "Kada.ro benötigte einen Online-Shop, der die Qualität und Ästhetik der Premium-Produkte widerspiegelt — Designermöbel und Dekor mit einem zum Markenimage passenden Einkaufserlebnis.",
        solution: "WooCommerce-Shop-Entwicklung mit Fokus auf das visuelle Erlebnis — intuitive Navigation nach Stil- und Raumkategorien, detaillierte Produktpräsentation, vereinfachter Bestellprozess und Design, das die Produkte in den Vordergrund stellt.",
        metrics: [
          { value: "Live", label: "Funktionaler Shop mit Hunderten von Produkten" },
          { value: "WooCommerce", label: "Skalierbare Plattform" },
          { value: "100%", label: "Zahlungs- & Lieferintegration" },
        ],
        timeline: "—",
        metaTitle: "Kada.ro – Premium-Möbel Online-Shop | Nesco Digital",
        metaDescription: "WooCommerce-Shop-Entwicklung für Kada.ro — Premium-Möbel und Heimdekoration mit einem hochwertigen visuellen Erlebnis und vollständiger Zahlungs- und Lieferintegration.",
      },
    },
  },
  {
    slug: "btfarch-world-architecture-festival",
    categories: ["Webdesign", "B2B"],
    tags: ["Webdesign", "B2B", "UI/UX", "Architecture"],
    services: ["Webdesign", "UI/UX", "Dezvoltare Website", "Arhitectură Vizuală"],
    heroImage: "/proiecte/btfarch-world-architecture-festival/hero.jpg",
    accentColor: "rgba(163,163,163,0.1)",
    accentText: "#a3a3a3",
    featured: false,
    i18n: {
      ro: {
        title: "Website pentru un birou de arhitectură nominalizat la World Architecture Festival",
        shortTitle: "BTFarch — WAF Shortlisted",
        metricMain: "WAF",
        metricSub: "Shortlisted",
        industry: "Arhitectură",
        description: "Redesign complet pentru a marca nominalizarea la unul dintre cele mai prestigioase premii din arhitectura mondială.",
        challenge: "Site-ul existent nu reflecta calitatea proiectelor biroului și nu era la nivelul unei nominalizări internaționale. Era nevoie de o prezență digitală care să comunice excelența arhitecturală.",
        solution: "Am realizat un redesign complet al website-ului, cu o arhitectură vizuală premium care pune în valoare portofoliul de proiecte și comunică standardele internaționale ale biroului.",
        metrics: [
          { value: "WAF 2024", label: "Shortlisted World Architecture Festival" },
          { value: "Premium", label: "identitate digitală aliniată internațional" },
          { value: "100%", label: "lansat înainte de ceremonia WAF" },
        ],
        timeline: "—",
        metaTitle: "BTFarch – Website Birou Arhitectură Nominalizat WAF | Nesco Digital",
        metaDescription: "Redesign complet al website-ului pentru un birou de arhitectură nominalizat la World Architecture Festival 2024.",
      },
      en: {
        title: "Website for an Architecture Firm Shortlisted at World Architecture Festival",
        shortTitle: "BTFarch — WAF Shortlisted",
        metricMain: "WAF",
        metricSub: "Shortlisted",
        industry: "Architecture",
        description: "Full redesign to mark the nomination at one of the most prestigious awards in world architecture.",
        challenge: "The existing site didn't reflect the quality of the firm's projects and wasn't up to the standard of an international nomination. A digital presence that communicates architectural excellence was needed.",
        solution: "We carried out a complete website redesign with a premium visual architecture that showcases the project portfolio and communicates the firm's international standards.",
        metrics: [
          { value: "WAF 2024", label: "Shortlisted World Architecture Festival" },
          { value: "Premium", label: "internationally aligned digital identity" },
          { value: "100%", label: "launched before the WAF ceremony" },
        ],
        timeline: "—",
        metaTitle: "BTFarch – Architecture Firm Website Shortlisted at WAF | Nesco Digital",
        metaDescription: "Full website redesign for an architecture firm shortlisted at the World Architecture Festival 2024.",
      },
      de: {
        title: "Website für ein beim World Architecture Festival nominiertes Architekturbüro",
        shortTitle: "BTFarch — WAF Shortlisted",
        metricMain: "WAF",
        metricSub: "Shortlisted",
        industry: "Architektur",
        description: "Komplettes Redesign zur Würdigung der Nominierung bei einem der renommiertesten Architekturpreise der Welt.",
        challenge: "Die bestehende Website spiegelte nicht die Qualität der Projekte des Büros wider und entsprach nicht dem Standard einer internationalen Nominierung.",
        solution: "Wir haben ein komplettes Website-Redesign mit einer hochwertigen visuellen Architektur durchgeführt, die das Projektportfolio präsentiert und die internationalen Standards des Büros kommuniziert.",
        metrics: [
          { value: "WAF 2024", label: "Shortlisted World Architecture Festival" },
          { value: "Premium", label: "international ausgerichtete digitale Identität" },
          { value: "100%", label: "vor der WAF-Zeremonie gestartet" },
        ],
        timeline: "—",
        metaTitle: "BTFarch – Architekturbüro-Website beim WAF nominiert | Nesco Digital",
        metaDescription: "Komplettes Website-Redesign für ein beim World Architecture Festival 2024 nominiertes Architekturbüro.",
      },
    },
  },
  {
    slug: "labianca-architecture",
    categories: ["Webdesign", "B2B"],
    tags: ["Webdesign", "Architecture", "UI/UX", "Branding"],
    services: ["Webdesign", "UI/UX", "Branding", "Visual Identity", "Dezvoltare Website"],
    heroImage: "/proiecte/labianca-architecture/hero.jpg",
    accentColor: "rgba(180,140,100,0.1)",
    accentText: "#d4a875",
    featured: false,
    i18n: {
      ro: {
        title: "Website & Identitate Vizuală – Labianca Architecture",
        shortTitle: "Labianca Architecture",
        metricMain: "Premium",
        metricSub: "Prezență digitală",
        industry: "Arhitectură",
        description: "Website premium și identitate vizuală pentru un birou de arhitectură — un spațiu digital care reflectă eleganța și minimalismul proiectelor lor.",
        challenge: "Biroul de arhitectură Labianca avea nevoie de o prezență digitală care să fie la nivelul calității proiectelor lor — elegantă, minimalistă și capabilă să atragă clienți premium.",
        solution: "Am creat un website cu un design minimalist de înaltă clasă, cu galerie vizuală impresionantă a proiectelor, animații subtile și o identitate vizuală coezivă care reflectă filosofia arhitecturală a biroului.",
        metrics: [
          { value: "Premium", label: "Identitate digitală" },
          { value: "100%", label: "Custom design" },
          { value: "Fast", label: "Performanță optimizată" },
        ],
        timeline: "—",
        metaTitle: "Labianca Architecture – Website & Identitate Vizuală | Nesco Digital",
        metaDescription: "Website premium și identitate vizuală pentru un birou de arhitectură — design minimalist care reflectă excelența proiectelor lor.",
      },
      en: {
        title: "Website & Visual Identity – Labianca Architecture",
        shortTitle: "Labianca Architecture",
        metricMain: "Premium",
        metricSub: "Digital presence",
        industry: "Architecture",
        description: "Premium website and visual identity for an architecture firm — a digital space that reflects the elegance and minimalism of their projects.",
        challenge: "Labianca Architecture needed a digital presence matching the quality of their projects — elegant, minimalist and capable of attracting premium clients.",
        solution: "We created a high-end minimalist website with an impressive project gallery, subtle animations, and a cohesive visual identity that reflects the firm's architectural philosophy.",
        metrics: [
          { value: "Premium", label: "Digital identity" },
          { value: "100%", label: "Custom design" },
          { value: "Fast", label: "Optimized performance" },
        ],
        timeline: "—",
        metaTitle: "Labianca Architecture – Website & Visual Identity | Nesco Digital",
        metaDescription: "Premium website and visual identity for an architecture firm — minimalist design reflecting the excellence of their projects.",
      },
      de: {
        title: "Website & Visuelle Identität – Labianca Architecture",
        shortTitle: "Labianca Architecture",
        metricMain: "Premium",
        metricSub: "Digitale Präsenz",
        industry: "Architektur",
        description: "Premium-Website und visuelle Identität für ein Architekturbüro — ein digitaler Raum, der die Eleganz und den Minimalismus ihrer Projekte widerspiegelt.",
        challenge: "Labianca Architecture benötigte eine digitale Präsenz, die dem Qualitätsniveau ihrer Projekte entspricht — elegant, minimalistisch und in der Lage, Premium-Kunden anzusprechen.",
        solution: "Wir haben eine hochwertige minimalistische Website mit einer beeindruckenden Projektgalerie, subtilen Animationen und einer kohärenten visuellen Identität erstellt, die die Architekturphilosophie des Büros widerspiegelt.",
        metrics: [
          { value: "Premium", label: "Digitale Identität" },
          { value: "100%", label: "Custom Design" },
          { value: "Fast", label: "Optimierte Performance" },
        ],
        timeline: "—",
        metaTitle: "Labianca Architecture – Website & Visuelle Identität | Nesco Digital",
        metaDescription: "Premium-Website und visuelle Identität für ein Architekturbüro — minimalistisches Design, das die Exzellenz ihrer Projekte widerspiegelt.",
      },
    },
  },
  {
    slug: "scalare-ecommerce-fmcg",
    categories: ["E-commerce", "Performance Marketing"],
    tags: ["E-Commerce", "Performance Marketing"],
    services: ["Meta Ads", "Google Ads", "Strategie Digitală", "CRO", "Email Marketing"],
    heroImage: "/proiecte/scalare-ecommerce-fmcg/hero.png",
    accentColor: "rgba(34,197,94,0.1)",
    accentText: "#22c55e",
    featured: false,
    i18n: {
      ro: {
        title: "De la lansare la lider de piață — scalare e-commerce produse de consum",
        shortTitle: "Scalare E-Commerce FMCG",
        metricMain: "2.000+",
        metricSub: "comenzi/zi",
        industry: "E-Commerce / FMCG",
        description: "Peste 2.000 de comenzi zilnice la peak. CPA sub 300 lei. LTV de 5× față de costul de achiziție în primul an. Bugete de ads scalate progresiv pe parcursul colaborării.",
        challenge: "Brand nou de e-commerce în categoria produse de consum, fără audiență, fără tracțiune, fără sistem de achiziție scalabil. Obiectivul: construirea unui motor de creștere profitabil de la zero.",
        solution: "Arhitectură completă de performance marketing — Meta Ads, Google Ads, structuri de campanii scalabile, optimizare continuă a CPA, sisteme de retenție și reactivare clienți pentru maximizarea LTV.",
        metrics: [
          { value: "2.000+", label: "comenzi/zi la peak" },
          { value: "<300 lei", label: "CPA" },
          { value: "5×", label: "LTV vs. cost achiziție (an 1)" },
        ],
        timeline: "—",
        metaTitle: "Scalare E-Commerce FMCG — 2.000+ comenzi/zi | Nesco Digital",
        metaDescription: "De la zero la 2.000+ comenzi zilnice prin performance marketing full-funnel — Meta Ads, Google Ads, CRO și sisteme de retenție.",
      },
      en: {
        title: "From launch to market leader — FMCG e-commerce scaling",
        shortTitle: "FMCG E-Commerce Scaling",
        metricMain: "2,000+",
        metricSub: "orders/day",
        industry: "E-Commerce / FMCG",
        description: "Over 2,000 daily orders at peak. CPA under 300 RON. LTV 5x the acquisition cost in the first year. Ad budgets scaled progressively throughout the collaboration.",
        challenge: "New e-commerce brand in the FMCG category, no audience, no traction, no scalable acquisition system. Objective: build a profitable growth engine from scratch.",
        solution: "Full performance marketing architecture — Meta Ads, Google Ads, scalable campaign structures, continuous CPA optimization, customer retention and reactivation systems for LTV maximization.",
        metrics: [
          { value: "2,000+", label: "orders/day at peak" },
          { value: "<300 RON", label: "CPA" },
          { value: "5×", label: "LTV vs. acquisition cost (year 1)" },
        ],
        timeline: "—",
        metaTitle: "FMCG E-Commerce Scaling — 2,000+ Orders/Day | Nesco Digital",
        metaDescription: "From zero to 2,000+ daily orders through full-funnel performance marketing — Meta Ads, Google Ads, CRO and retention systems.",
      },
      de: {
        title: "Von der Markteinführung zur Marktführerschaft — FMCG E-Commerce Skalierung",
        shortTitle: "FMCG E-Commerce Skalierung",
        metricMain: "2.000+",
        metricSub: "Bestellungen/Tag",
        industry: "E-Commerce / FMCG",
        description: "Über 2.000 tägliche Bestellungen auf dem Höhepunkt. CPA unter 300 RON. LTV 5x die Akquisitionskosten im ersten Jahr. Werbebudgets wurden während der Zusammenarbeit schrittweise skaliert.",
        challenge: "Neue E-Commerce-Marke im FMCG-Bereich, keine Zielgruppe, keine Traktion, kein skalierbares Akquisitionssystem. Ziel: Aufbau einer profitablen Wachstumsmaschine von Grund auf.",
        solution: "Vollständige Performance-Marketing-Architektur — Meta Ads, Google Ads, skalierbare Kampagnenstrukturen, kontinuierliche CPA-Optimierung, Kundenbindungs- und Reaktivierungssysteme zur LTV-Maximierung.",
        metrics: [
          { value: "2.000+", label: "Bestellungen/Tag auf dem Höhepunkt" },
          { value: "<300 RON", label: "CPA" },
          { value: "5×", label: "LTV vs. Akquisitionskosten (Jahr 1)" },
        ],
        timeline: "—",
        metaTitle: "FMCG E-Commerce Skalierung — 2.000+ Bestellungen/Tag | Nesco Digital",
        metaDescription: "Von null auf 2.000+ tägliche Bestellungen durch Full-Funnel Performance Marketing — Meta Ads, Google Ads, CRO und Kundenbindungssysteme.",
      },
    },
  },
  {
    slug: "sistem-vanzare-educatie-online",
    categories: ["Online Education", "Performance Marketing"],
    tags: ["Online Education", "Performance Marketing"],
    services: ["Meta Ads", "TikTok Ads", "Email Marketing", "SMS Marketing", "Funnel Design", "Strategie Digitală"],
    heroImage: undefined,
    accentColor: "rgba(86,219,132,0.1)",
    accentText: "#56db84",
    featured: false,
    i18n: {
      ro: {
        title: "De la audiență la 400.000 lei/lună — sistem complet de vânzare pentru educație online",
        shortTitle: "Sistem Vânzare Educație Online",
        metricMain: "400k lei",
        metricSub: "revenue lunar consistent",
        industry: "Educație Online",
        description: "300.000-400.000 lei revenue lunar consistent. Cost per lead 8-12 lei. Rată de conversie webinar 5-7%. Listă de email activă de peste 20.000 abonați. Sistem de vânzare care rulează independent de prezența constantă a fondatorului.",
        challenge: "Brand de educație online cu audiență existentă dar fără sistem structurat de vânzare. Lansările erau manuale, impredictibile și dependente de efort constant. Lipseau funnel-urile, automatizările și infrastructura de email și SMS.",
        solution: "Construirea unui sistem complet de revenue — funnel de webinar automatizat, campanii Meta Ads și TikTok Ads pentru generare de lead-uri la 8-12 lei, secvențe de email și SMS pentru nurturing și conversie, lansări structurate cu pre-sell și follow-up automatizat.",
        metrics: [
          { value: "400k lei", label: "revenue lunar la peak" },
          { value: "8-12 lei", label: "cost per lead" },
          { value: "5-7%", label: "rată conversie webinar" },
          { value: "20.000+", label: "abonați email activi" },
        ],
        timeline: "—",
        metaTitle: "400.000 lei/lună — Sistem Vânzare Educație Online | Nesco Digital",
        metaDescription: "De la audiență la 400.000 lei revenue lunar prin funnel de webinar automatizat, Meta Ads, TikTok Ads și secvențe email + SMS.",
      },
      en: {
        title: "From audience to €80k/month — full sales system for online education",
        shortTitle: "Online Education Sales System",
        metricMain: "€80k",
        metricSub: "consistent monthly revenue",
        industry: "Online Education",
        description: "300,000-400,000 RON consistent monthly revenue. Cost per lead 8-12 RON. Webinar conversion rate 5-7%. Active email list of 20,000+ subscribers. Sales system running independently of the founder's constant presence.",
        challenge: "Online education brand with existing audience but no structured sales system. Launches were manual, unpredictable and dependent on constant effort. Missing funnels, automations and email/SMS infrastructure.",
        solution: "Building a complete revenue system — automated webinar funnel, Meta Ads and TikTok Ads campaigns generating leads at 8-12 RON, email and SMS sequences for nurturing and conversion, structured launches with pre-sell and automated follow-up.",
        metrics: [
          { value: "€80k", label: "monthly revenue at peak" },
          { value: "8-12 RON", label: "cost per lead" },
          { value: "5-7%", label: "webinar conversion rate" },
          { value: "20,000+", label: "active email subscribers" },
        ],
        timeline: "—",
        metaTitle: "€80k/Month — Online Education Sales System | Nesco Digital",
        metaDescription: "From audience to €80k monthly revenue through automated webinar funnel, Meta Ads, TikTok Ads and email + SMS sequences.",
      },
      de: {
        title: "Von der Zielgruppe zu 80.000€/Monat — vollständiges Verkaufssystem für Online-Bildung",
        shortTitle: "Online-Bildung Verkaufssystem",
        metricMain: "80.000€",
        metricSub: "konsistenter Monatsumsatz",
        industry: "Online-Bildung",
        description: "300.000-400.000 RON konsistenter monatlicher Umsatz. Cost per Lead 8-12 RON. Webinar-Konversionsrate 5-7%. Aktive E-Mail-Liste mit über 20.000 Abonnenten.",
        challenge: "Online-Bildungsmarke mit vorhandener Zielgruppe aber ohne strukturiertes Verkaufssystem. Launches waren manuell, unvorhersehbar und von konstantem Aufwand abhängig.",
        solution: "Aufbau eines vollständigen Umsatzsystems — automatisierter Webinar-Funnel, Meta Ads und TikTok Ads Kampagnen mit Leads bei 8-12 RON, E-Mail- und SMS-Sequenzen für Nurturing und Conversion.",
        metrics: [
          { value: "80.000€", label: "Monatsumsatz auf dem Höhepunkt" },
          { value: "8-12 RON", label: "Cost per Lead" },
          { value: "5-7%", label: "Webinar-Konversionsrate" },
          { value: "20.000+", label: "aktive E-Mail-Abonnenten" },
        ],
        timeline: "—",
        metaTitle: "80.000€/Monat — Online-Bildung Verkaufssystem | Nesco Digital",
        metaDescription: "Von der Zielgruppe zu 80.000€ Monatsumsatz durch automatisierten Webinar-Funnel, Meta Ads, TikTok Ads und E-Mail + SMS Sequenzen.",
      },
    },
  },
];

export function getProjectBySlug(slug: string): Project | undefined {
  return projects.find((p) => p.slug === slug);
}

export function getProjectsByCategory(category: ProjectCategory): Project[] {
  return projects.filter((p) => p.categories.includes(category));
}

export const ALL_CATEGORIES: ProjectCategory[] = ["B2B", "E-commerce", "SaaS", "DTC", "Sănătate", "Performance Marketing", "Online Education", "Growth Sprint", "Webdesign"];
