import type { ServicePageData } from "@/components/sections/ServicePage";

// ─── Google Ads ───────────────────────────────────────────────────────────────
export const googleAdsData: Record<"ro" | "en" | "de", ServicePageData> = {
  ro: {
    locale: "ro",
    breadcrumbCategory: "paidAds",
    hero: {
      badge: "Google Ads",
      title: "Fii acolo când clientul tău te caută pe Google",
      subtitle:
        "73% dintre oameni caută online înainte de orice achiziție. Cu Google Ads, afacerea ta apare exact când cineva caută ce oferi tu, nu mai aștepți să te găsească, ești acolo în momentul cheie.",
    },
    problems: [
      { title: "Clienții te caută, dar găsesc concurenții", desc: "Apari pe pagina 3-4 a Google, unde nimeni nu ajunge. Clienții potențiali găsesc concurenții tăi în locul tău." },
      { title: "SEO-ul durează 6-12 luni", desc: "Nu îți poți permite să aștepți un an pentru trafic. Afacerea ta are nevoie de clienți acum, nu în viitor." },
      { title: "Social media nu ajunge la cine caută activ", desc: "Un om care caută \"service auto București\" pe Google e gata să cumpere. Pe Facebook, doar te-a văzut întâmplător." },
      { title: "Nu știi câți clienți pierzi zilnic", desc: "Fără date clare, conduci cu ochii închiși. Cu Google Ads știi exact ce buget a generat câți clienți." },
    ],
    solutions: [
      { title: "Search Ads, Apari primul când contează", desc: "Reclamele tale apar în primele poziții când cineva caută exact serviciul sau produsul tău. Plătești doar când face click." },
      { title: "Shopping Ads, Produsul tău cu preț și imagine", desc: "Perfect pentru magazine online: produsele tale apar vizual în rezultatele Google, cu preț, recenzii și link direct." },
      { title: "Display, Fii văzut pe tot internetul", desc: "Reclame vizuale pe milioane de site-uri partenere Google. Ideal pentru brand awareness și remarketing." },
      { title: "YouTube Ads, Video înainte de conținut relevant", desc: "Reclamele tale video apar înainte de conținut relevant pe YouTube, cea mai mare platformă video din lume." },
      { title: "Remarketing, Readu clienții care te-au uitat", desc: "97% din vizitatori nu cumpără la prima vizită. Remarketing-ul le reamintește de tine cu mesaje relevante până convertesc." },
      { title: "Raportare 100% transparentă", desc: "Știi exact câți lei au generat câte conversii. Nu există cheltuieli ascunse sau rezultate vagi." },
    ],
    cases: [
      { metric: "38% mai mic", label: "Cost per achiziție (CPA)", industry: "E-commerce" },
      { metric: "+30%", label: "Creștere conversii în 3 luni", industry: "Retail" },
      { metric: "+200%", label: "Creștere vânzări în 6 luni", industry: "E-commerce" },
      { metric: "25% redus", label: "Cost per achiziție", industry: "B2B" },
      { metric: "+150%", label: "Lead-uri calificate", industry: "Educație" },
      { metric: "5x ROAS", label: "Return on Ad Spend", industry: "Fashion" },
    ],
    omnichannelServices: ["Facebook Ads", "Instagram Ads", "TikTok Ads", "SEO", "Email Marketing", "CRO"],
    faq: [
      { q: "Am deja SEO, mai am nevoie de Google Ads?", a: "SEO și Google Ads se completează, nu se înlocuiesc. SEO construiește prezența pe termen lung (6-12 luni), în timp ce Google Ads îți aduce clienți imediat. Clienții noștri care le folosesc pe ambele obțin cele mai bune rezultate, Google Ads acoperă perioada în care SEO se construiește." },
      { q: "Cum funcționează? Plătesc pentru fiecare click?", a: "Da, Google Ads funcționează pe sistem PPC (pay-per-click). Plătești doar când cineva face click pe reclama ta, nu când o vede. Licitezi pentru cuvinte cheie relevante și Google afișează reclama ta utilizatorilor care le caută." },
      { q: "De cât buget am nevoie ca să fie eficient?", a: "Recomandăm minimum 500€/lună în buget de reclame pentru a obține date suficiente pentru optimizare. Sub această sumă, algoritmul Google nu are suficienți utilizatori pentru a învăța și optimiza. Onorariul nostru de management este separat de bugetul de reclame." },
      { q: "Cât de repede văd rezultate?", a: "Primele click-uri și vizite apar în 24-48 ore de la lansare. Conversiile (vânzări, lead-uri) apar de obicei în prima săptămână dacă site-ul tău este bine pregătit. Optimizarea completă durează 2-4 săptămâni." },
      { q: "Pot concura cu firme mari care au bugete mari?", a: "Da, cu strategie inteligentă. Nu concurezi pe cuvinte generale (scumpe), ci pe cuvinte cheie de nișă specifice business-ului tău unde concurenții nu licitează. Uneori un buget mic și bine direcționat bate un buget mare prost administrat." },
      { q: "Ce se întâmplă dacă opresc campaniile?", a: "Traficul se oprește imediat. Spre deosebire de SEO care rămâne, Google Ads funcționează cât timp bugetul este activ. De aceea recomandăm o strategie combinată: Google Ads pentru rezultate imediate + SEO pentru sustenabilitate pe termen lung." },
    ],
    testimonial: { quote: "În 3 luni, costul per lead a scăzut cu 40% și volumul de leads a crescut de 2x. Echipa Nesco a restructurat complet contul nostru și a schimbat abordarea de targeting.", name: "Mihai D.", role: "CEO, companie de software B2B, București" },
    tools: ["Google Ads", "Google Analytics 4", "Google Tag Manager", "Google Merchant Center", "Looker Studio"],
    toolsSectionTitle: "INSTRUMENTELE PE CARE LE FOLOSIM",
    freeAuditBadge: "Audit Google Ads Gratuit Inclus",
  },
  en: {
    locale: "en",
    breadcrumbCategory: "paidAds",
    hero: {
      badge: "Google Ads",
      title: "Be there when your customer searches for you on Google",
      subtitle:
        "73% of people search online before any purchase. With Google Ads, your business appears exactly when someone searches for what you offer. You stop waiting to be found, you're there at the key moment.",
    },
    problems: [
      { title: "Customers search but find your competitors", desc: "You appear on page 3-4 of Google, where nobody goes. Potential clients find your competitors instead of you." },
      { title: "SEO takes 6-12 months", desc: "You can't afford to wait a year for traffic. Your business needs customers now, not in the future." },
      { title: "Social media doesn't reach active searchers", desc: "Someone searching 'car repair London' on Google is ready to buy. On Facebook, they just happened to see you." },
      { title: "You don't know how many customers you lose daily", desc: "Without clear data, you're driving blind. With Google Ads you know exactly what budget generated how many customers." },
    ],
    solutions: [
      { title: "Search Ads, Appear first when it matters", desc: "Your ads appear in top positions when someone searches for exactly your service or product. You only pay when they click." },
      { title: "Shopping Ads, Your product with price and image", desc: "Perfect for online stores: your products appear visually in Google results, with price, reviews and a direct link." },
      { title: "Display, Be seen across the internet", desc: "Visual ads on millions of Google partner websites. Ideal for brand awareness and remarketing." },
      { title: "YouTube Ads, Video before relevant content", desc: "Your video ads appear before relevant content on YouTube, the world's largest video platform." },
      { title: "Remarketing, Bring back customers who forgot you", desc: "97% of visitors don't buy on the first visit. Remarketing reminds them of you with relevant messages until they convert." },
      { title: "100% transparent reporting", desc: "You know exactly how many euros generated how many conversions. No hidden costs or vague results." },
    ],
    cases: [
      { metric: "38% lower", label: "Cost per acquisition (CPA)", industry: "E-commerce" },
      { metric: "+30%", label: "Conversion increase in 3 months", industry: "Retail" },
      { metric: "+200%", label: "Sales increase in 6 months", industry: "E-commerce" },
      { metric: "25% reduced", label: "Cost per acquisition", industry: "B2B" },
      { metric: "+150%", label: "Qualified leads", industry: "Education" },
      { metric: "5x ROAS", label: "Return on Ad Spend", industry: "Fashion" },
    ],
    omnichannelServices: ["Facebook Ads", "Instagram Ads", "TikTok Ads", "SEO", "Email Marketing", "CRO"],
    faq: [
      { q: "I already have SEO, do I need Google Ads?", a: "SEO and Google Ads complement each other, they don't replace each other. SEO builds long-term presence (6-12 months), while Google Ads brings customers immediately. Our clients who use both get the best results, Google Ads covers the period while SEO is being built." },
      { q: "How does it work? Do I pay per click?", a: "Yes, Google Ads works on a PPC (pay-per-click) system. You only pay when someone clicks on your ad, not when they see it. You bid on relevant keywords and Google shows your ad to users who search for them." },
      { q: "How much budget do I need to be effective?", a: "We recommend a minimum of €500/month in ad spend to get enough data for optimization. Below this amount, Google's algorithm doesn't have enough users to learn and optimize. Our management fee is separate from the ad budget." },
      { q: "How quickly will I see results?", a: "First clicks and visits appear within 24-48 hours of launch. Conversions (sales, leads) typically appear in the first week if your website is well prepared. Full optimization takes 2-4 weeks." },
      { q: "Can I compete with large companies with big budgets?", a: "Yes, with smart strategy. You don't compete on general (expensive) keywords, but on niche keywords specific to your business where competitors don't bid. A small, well-directed budget often beats a large, poorly managed one." },
      { q: "What happens if I stop the campaigns?", a: "Traffic stops immediately. Unlike SEO which persists, Google Ads works while the budget is active. That's why we recommend a combined strategy: Google Ads for immediate results + SEO for long-term sustainability." },
    ],
    testimonial: { quote: "In 3 months, cost per lead dropped 40% and lead volume doubled. Nesco completely restructured our account and changed our targeting approach.", name: "Michael D.", role: "CEO, B2B Software Company, London" },
    tools: ["Google Ads", "Google Analytics 4", "Google Tag Manager", "Google Merchant Center", "Looker Studio"],
    toolsSectionTitle: "TOOLS WE USE",
    freeAuditBadge: "Free Google Ads Audit Included",
  },
  de: {
    locale: "de",
    breadcrumbCategory: "paidAds",
    hero: {
      badge: "Google Ads",
      title: "Seien Sie da, wenn Ihr Kunde auf Google nach Ihnen sucht",
      subtitle:
        "73% der Menschen suchen online, bevor sie einen Kauf tätigen. Mit Google Ads erscheint Ihr Unternehmen genau dann, wenn jemand nach dem sucht, was Sie anbieten. Sie warten nicht darauf, gefunden zu werden, Sie sind im entscheidenden Moment da.",
    },
    problems: [
      { title: "Kunden suchen, finden aber Ihre Mitbewerber", desc: "Sie erscheinen auf Seite 3-4 von Google, wo niemand hinkommt. Potenzielle Kunden finden stattdessen Ihre Konkurrenten." },
      { title: "SEO dauert 6-12 Monate", desc: "Sie können es sich nicht leisten, ein Jahr auf Traffic zu warten. Ihr Unternehmen braucht jetzt Kunden, nicht in der Zukunft." },
      { title: "Social Media erreicht keine aktiven Sucher", desc: "Jemand, der auf Google nach 'Autowerkstatt München' sucht, ist kaufbereit. Auf Facebook haben sie Sie nur zufällig gesehen." },
      { title: "Sie wissen nicht, wie viele Kunden Sie täglich verlieren", desc: "Ohne klare Daten fahren Sie blind. Mit Google Ads wissen Sie genau, welches Budget wie viele Kunden generiert hat." },
    ],
    solutions: [
      { title: "Search Ads, Erscheinen Sie zuerst, wenn es darauf ankommt", desc: "Ihre Anzeigen erscheinen auf den obersten Positionen, wenn jemand nach genau Ihrem Service oder Produkt sucht. Sie zahlen nur, wenn geklickt wird." },
      { title: "Shopping Ads, Ihr Produkt mit Preis und Bild", desc: "Perfekt für Online-Shops: Ihre Produkte erscheinen visuell in Google-Ergebnissen, mit Preis, Bewertungen und direktem Link." },
      { title: "Display, Seien Sie im gesamten Internet sichtbar", desc: "Visuelle Anzeigen auf Millionen von Google-Partner-Websites. Ideal für Brand Awareness und Remarketing." },
      { title: "YouTube Ads, Video vor relevantem Content", desc: "Ihre Video-Anzeigen erscheinen vor relevanten Inhalten auf YouTube, der weltweit größten Videoplattform." },
      { title: "Remarketing, Bringen Sie Kunden zurück, die Sie vergessen haben", desc: "97% der Besucher kaufen beim ersten Besuch nicht. Remarketing erinnert sie mit relevanten Botschaften an Sie, bis sie konvertieren." },
      { title: "100% transparentes Reporting", desc: "Sie wissen genau, wie viele Euro wie viele Conversions generiert haben. Keine versteckten Kosten oder vagen Ergebnisse." },
    ],
    cases: [
      { metric: "38% niedriger", label: "Cost per Acquisition (CPA)", industry: "E-Commerce" },
      { metric: "+30%", label: "Conversion-Steigerung in 3 Monaten", industry: "Einzelhandel" },
      { metric: "+200%", label: "Umsatzsteigerung in 6 Monaten", industry: "E-Commerce" },
      { metric: "25% reduziert", label: "Cost per Acquisition", industry: "B2B" },
      { metric: "+150%", label: "Qualifizierte Leads", industry: "Bildung" },
      { metric: "5x ROAS", label: "Return on Ad Spend", industry: "Mode" },
    ],
    omnichannelServices: ["Facebook Ads", "Instagram Ads", "TikTok Ads", "SEO", "E-Mail-Marketing", "CRO"],
    faq: [
      { q: "Ich habe bereits SEO, brauche ich Google Ads?", a: "SEO und Google Ads ergänzen sich, sie ersetzen sich nicht. SEO baut langfristige Präsenz auf (6-12 Monate), während Google Ads sofort Kunden bringt. Unsere Kunden, die beides nutzen, erzielen die besten Ergebnisse, Google Ads deckt den Zeitraum ab, in dem SEO aufgebaut wird." },
      { q: "Wie funktioniert es? Zahle ich pro Klick?", a: "Ja, Google Ads funktioniert auf einem PPC-System (Pay-per-Click). Sie zahlen nur, wenn jemand auf Ihre Anzeige klickt, nicht wenn er sie sieht. Sie bieten auf relevante Keywords und Google zeigt Ihre Anzeige Nutzern, die danach suchen." },
      { q: "Wie viel Budget brauche ich, um effektiv zu sein?", a: "Wir empfehlen mindestens 500 €/Monat an Werbeausgaben, um genug Daten für die Optimierung zu erhalten. Darunter hat Googles Algorithmus nicht genug Nutzer, um zu lernen und zu optimieren. Unsere Management-Gebühr ist vom Werbebudget getrennt." },
      { q: "Wie schnell sehe ich Ergebnisse?", a: "Erste Klicks und Besuche erscheinen innerhalb von 24-48 Stunden nach dem Start. Conversions erscheinen typischerweise in der ersten Woche, wenn Ihre Website gut vorbereitet ist. Die vollständige Optimierung dauert 2-4 Wochen." },
      { q: "Kann ich mit großen Unternehmen mit hohen Budgets konkurrieren?", a: "Ja, mit cleverer Strategie. Sie konkurrieren nicht auf allgemeinen (teuren) Keywords, sondern auf Nischen-Keywords, die spezifisch für Ihr Unternehmen sind, wo Mitbewerber nicht bieten. Ein kleines, gut gesteuertes Budget schlägt oft ein großes, schlecht verwaltetes Budget." },
      { q: "Was passiert, wenn ich die Kampagnen stoppe?", a: "Der Traffic stoppt sofort. Anders als SEO, das bestehen bleibt, funktioniert Google Ads, solange das Budget aktiv ist. Deshalb empfehlen wir eine kombinierte Strategie: Google Ads für sofortige Ergebnisse + SEO für langfristige Nachhaltigkeit." },
    ],
    testimonial: { quote: "In 3 Monaten sank der Cost-per-Lead um 40% und das Lead-Volumen verdoppelte sich. Das Nesco-Team hat unser Konto komplett restrukturiert.", name: "Michael D.", role: "CEO, B2B-Softwareunternehmen" },
    tools: ["Google Ads", "Google Analytics 4", "Google Tag Manager", "Google Merchant Center", "Looker Studio"],
    toolsSectionTitle: "UNSERE TOOLS",
    freeAuditBadge: "Kostenloser Google Ads Audit Inklusive",
  },
};

// ─── Facebook Ads ─────────────────────────────────────────────────────────────
export const facebookAdsData: Record<"ro" | "en" | "de", ServicePageData> = {
  ro: {
    locale: "ro",
    breadcrumbCategory: "paidAds",
    hero: {
      badge: "Facebook Ads",
      title: "Ajunge la viitorii tăi clienți înainte ca ei să te caute",
      subtitle:
        "Facebook are 9 milioane de utilizatori activi în România. Cu targetarea avansată Meta, reclamele tale ajung exact la persoanele care seamănă cu clienții tăi existenți, chiar dacă ei nu știu încă că au nevoie de tine.",
    },
    problems: [
      { title: "Reach-ul organic a scăzut la 3-5%", desc: "Postezi constant pe Facebook, dar doar o mică parte din urmăritori văd postările. Facebook prioritizează conținutul prietenilor față de cel al brandurilor." },
      { title: "Nu știi unde sunt clienții tăi online", desc: "Fără date de targetare, \"arunci\" mesaje la întâmplare sperând să nimerești audiența potrivită." },
      { title: "Concurenții ajung la audiența ta", desc: "Dacă tu nu faci Facebook Ads, concurenții tăi o fac. Audiențele pe care le-ai putea câștiga sunt servite altora." },
      { title: "Mesajele tale nu ajung la momentul potrivit", desc: "O persoană interesată de vacanță trebuie să vadă reclama ta vinerea. Organic, nu poți controla asta." },
    ],
    solutions: [
      { title: "Targeting după interese și comportament", desc: "Ajungem la oameni interesați de exact ce vinzi tu: hobby-uri, comportamente de cumpărare, venituri, locație și mult mai mult." },
      { title: "Lookalike Audiences, clienți ca ai tăi", desc: "Uploadăm lista ta de clienți existenți și Facebook găsește automat milioane de oameni similari din România sau Europa." },
      { title: "Creative care opresc scroll-ul", desc: "Video de 15-30 secunde și imagini autentice care captează atenția în primele 3 secunde, singura modalitate de a bate algoritmul." },
      { title: "Funnel complet, de la awareness la vânzare", desc: "Expunem brandul tău oamenilor noi, reconectăm cu cei interesați și convertim cei care au vizitat site-ul." },
      { title: "Retargeting, readu-i pe cei interesați", desc: "97% din vizitatori nu cumpără la prima vizită. Retargeting-ul le reamintește de tine cu mesaje relevante." },
      { title: "Raportare și optimizare continuă", desc: "Urmărim costul per lead sau vânzare, nu clicuri sau like-uri care nu înseamnă nimic pentru business." },
    ],
    cases: [
      { metric: "30% mai mic", label: "Cost per Lead față de medie", industry: "B2B" },
      { metric: "+45%", label: "ROAS în 60 de zile", industry: "E-commerce Fashion" },
      { metric: "3x leads", label: "Volume de lead-uri calificate", industry: "Imobiliare" },
      { metric: "-40%", label: "Cost per Achiziție", industry: "Retail" },
      { metric: "+120%", label: "Conversii din Retargeting", industry: "Cosmetice" },
      { metric: "2.5x ROAS", label: "Return on Ad Spend", industry: "Sports" },
    ],
    omnichannelServices: ["Google Ads", "Instagram Ads", "TikTok Ads", "CRO", "Email Marketing"],
    faq: [
      { q: "Nu mai are nimeni Facebook?", a: "Cu 9 milioane de utilizatori activi în România (din care 60% sunt adulți cu putere de cumpărare), Facebook este încă cea mai mare rețea socială din țară. Plus că Meta include și Instagram în aceleași campanii." },
      { q: "Eu postez deja pe Facebook, ce face paid diferit?", a: "Postările organice ajung la 3-5% din urmăritori. Reclamele plătite ajung exact la audiența definită de tine, sute de mii sau milioane de persoane, nu doar la cei care te urmăresc deja." },
      { q: "De cât buget am nevoie pentru Facebook Ads?", a: "Recomandăm minimum 300-500€/lună în buget de reclame. Cu mai puțin, datele sunt insuficiente pentru optimizare. Rezultatele devin semnificativ mai bune după 60 de zile când algoritmul a învățat audiența ta." },
      { q: "Funcționează Facebook Ads pentru B2B?", a: "Da, dar cu strategie diferită. Targetăm după job title, industrie și dimensiunea companiei. Pentru B2B enterprise, LinkedIn poate fi mai eficient, te ajutăm să decizi ce funcționează pentru business-ul tău." },
      { q: "Ce tip de conținut trebuie să pregătesc?", a: "Noi ne ocupăm de strategie și copy. Avem nevoie de câteva imagini cu produsele/serviciile tale și eventual un video scurt (chiar și filmat cu telefonul). O imagine autentică funcționează mai bine decât una perfectă pe Facebook." },
      { q: "Cum știu că reclamele mele performează cu adevărat?", a: "Prin rapoarte săptămânale cu toate metricile: reach, frecvență, cost per click, cost per lead, cost per vânzare și ROAS. Nu ascundem nicio dată, chiar dacă rezultatele nu sunt la nivel maxim, ești primul care știe." },
    ],
    testimonial: { quote: "ROAS de 6.2x pe campaniile de Black Friday. Nesco a creat o strategie completă de funnel care a funcționat mult mai bine decât ce făceam noi intern.", name: "Bogdan R.", role: "Fondator, brand de cosmetice naturale" },
    tools: ["Meta Ads Manager", "Meta Pixel", "Meta Business Suite", "Google Analytics 4", "Klaviyo"],
    toolsSectionTitle: "INSTRUMENTELE PE CARE LE FOLOSIM",
    freeAuditBadge: "Audit Facebook Ads Gratuit Inclus",
  },
  en: {
    locale: "en",
    breadcrumbCategory: "paidAds",
    hero: {
      badge: "Facebook Ads",
      title: "Reach your future customers before they search for you",
      subtitle:
        "Facebook has nearly 3 billion active users worldwide. With Meta's advanced targeting, your ads reach exactly the people who look like your existing customers, even if they don't yet know they need you.",
    },
    problems: [
      { title: "Organic reach dropped to 3-5%", desc: "You post constantly on Facebook but only a fraction of your followers see your posts. Facebook prioritizes friends' content over brand content." },
      { title: "You don't know where your customers are online", desc: "Without targeting data, you're throwing messages randomly hoping to hit the right audience." },
      { title: "Competitors are reaching your audience", desc: "If you're not running Facebook Ads, your competitors are. The audiences you could win are being served to others." },
      { title: "Your messages don't reach at the right time", desc: "Someone interested in a weekend getaway needs to see your ad on Friday. Organically, you can't control that." },
    ],
    solutions: [
      { title: "Interest and behavior targeting", desc: "We reach people interested in exactly what you sell: hobbies, purchase behaviors, income, location, and much more." },
      { title: "Lookalike Audiences, customers like yours", desc: "We upload your existing customer list and Facebook automatically finds millions of similar people in your country or Europe." },
      { title: "Creative that stops the scroll", desc: "15-30 second videos and authentic images that capture attention in the first 3 seconds, the only way to beat the algorithm." },
      { title: "Full funnel, from awareness to sale", desc: "We expose your brand to new people, reconnect with those who showed interest, and convert those who visited your site." },
      { title: "Retargeting, bring back those who were interested", desc: "97% of visitors don't buy on the first visit. Retargeting reminds them of you with relevant messages." },
      { title: "Reporting and continuous optimization", desc: "We track cost per lead or sale, not clicks or likes that don't mean anything for your business." },
    ],
    cases: [
      { metric: "30% lower", label: "Cost per lead vs. average", industry: "B2B" },
      { metric: "+45%", label: "ROAS in 60 days", industry: "E-commerce Fashion" },
      { metric: "3x leads", label: "Qualified lead volume", industry: "Real Estate" },
      { metric: "-40%", label: "Cost per Acquisition", industry: "Retail" },
      { metric: "+120%", label: "Retargeting conversions", industry: "Cosmetics" },
      { metric: "2.5x ROAS", label: "Return on Ad Spend", industry: "Sports" },
    ],
    omnichannelServices: ["Google Ads", "Instagram Ads", "TikTok Ads", "CRO", "Email Marketing"],
    faq: [
      { q: "Does anyone still use Facebook?", a: "With nearly 3 billion monthly active users worldwide, Facebook remains the largest social network globally. Plus Meta includes Instagram in the same campaigns, giving you reach on both platforms." },
      { q: "I already post on Facebook, what does paid do differently?", a: "Organic posts reach 3-5% of your followers. Paid ads reach exactly the audience you define, potentially hundreds of thousands or millions of people, not just those who already follow you." },
      { q: "How much budget do I need for Facebook Ads?", a: "We recommend a minimum of €300-500/month in ad spend. Below that, data is insufficient for optimization. Results improve significantly after 60 days when the algorithm has learned your audience." },
      { q: "Does Facebook Ads work for B2B?", a: "Yes, but with a different strategy. We target by job title, industry, and company size. For enterprise B2B, LinkedIn can be more effective, we help you decide what works for your business." },
      { q: "What content do I need to prepare?", a: "We handle strategy and copy. We need a few images of your products/services and optionally a short video (even filmed on your phone). Authentic works better than perfect on Facebook." },
      { q: "How do I know my ads are really performing?", a: "Through weekly reports with all metrics: reach, frequency, cost per click, cost per lead, cost per sale and ROAS. We hide nothing, even if results aren't at maximum level, you're the first to know." },
    ],
    testimonial: { quote: "6.2x ROAS on our Black Friday campaigns. Nesco created a complete funnel strategy that worked far better than what we were doing in-house.", name: "Bogdan R.", role: "Founder, natural cosmetics brand" },
    tools: ["Meta Ads Manager", "Meta Pixel", "Meta Business Suite", "Google Analytics 4", "Klaviyo"],
    toolsSectionTitle: "TOOLS WE USE",
    freeAuditBadge: "Free Facebook Ads Audit Included",
  },
  de: {
    locale: "de",
    breadcrumbCategory: "paidAds",
    hero: {
      badge: "Facebook Ads",
      title: "Erreichen Sie Ihre zukünftigen Kunden, bevor sie Sie suchen",
      subtitle:
        "Facebook hat fast 3 Milliarden aktive Nutzer weltweit. Mit Metas fortschrittlichem Targeting erreichen Ihre Anzeigen genau die Menschen, die Ihren bestehenden Kunden ähneln, auch wenn sie noch nicht wissen, dass sie Sie brauchen.",
    },
    problems: [
      { title: "Organische Reichweite auf 3-5% gesunken", desc: "Sie posten ständig auf Facebook, aber nur ein Bruchteil Ihrer Follower sieht Ihre Beiträge. Facebook priorisiert Inhalte von Freunden gegenüber Markeninhalten." },
      { title: "Sie wissen nicht, wo Ihre Kunden online sind", desc: "Ohne Targeting-Daten werfen Sie Nachrichten zufällig aus und hoffen, die richtige Zielgruppe zu treffen." },
      { title: "Mitbewerber erreichen Ihre Zielgruppe", desc: "Wenn Sie keine Facebook Ads schalten, tun es Ihre Konkurrenten. Die Zielgruppen, die Sie gewinnen könnten, werden anderen serviert." },
      { title: "Ihre Botschaften kommen nicht zur richtigen Zeit an", desc: "Jemand, der an einem Wochenendausflug interessiert ist, muss Ihre Anzeige freitags sehen. Organisch können Sie das nicht kontrollieren." },
    ],
    solutions: [
      { title: "Interesse- und Verhaltens-Targeting", desc: "Wir erreichen Menschen, die an genau dem interessiert sind, was Sie verkaufen: Hobbys, Kaufverhalten, Einkommen, Standort und vieles mehr." },
      { title: "Lookalike Audiences, Kunden wie Ihre", desc: "Wir laden Ihre bestehende Kundenliste hoch und Facebook findet automatisch Millionen ähnlicher Menschen in Ihrem Land oder Europa." },
      { title: "Creative, das den Scroll stoppt", desc: "15-30 Sekunden Videos und authentische Bilder, die in den ersten 3 Sekunden Aufmerksamkeit erregen, der einzige Weg, den Algorithmus zu schlagen." },
      { title: "Vollständiger Funnel, von Awareness bis zum Verkauf", desc: "Wir setzen Ihre Marke bei neuen Menschen aus, reconnecten mit Interessierten und konvertieren diejenigen, die Ihre Website besucht haben." },
      { title: "Retargeting, bringen Sie Interessierte zurück", desc: "97% der Besucher kaufen beim ersten Besuch nicht. Retargeting erinnert sie mit relevanten Botschaften an Sie." },
      { title: "Reporting und kontinuierliche Optimierung", desc: "Wir verfolgen Kosten pro Lead oder Verkauf, keine Klicks oder Likes, die für Ihr Geschäft nichts bedeuten." },
    ],
    cases: [
      { metric: "30% niedriger", label: "Cost per Lead vs. Durchschnitt", industry: "B2B" },
      { metric: "+45%", label: "ROAS in 60 Tagen", industry: "E-Commerce Fashion" },
      { metric: "3x Leads", label: "Qualifiziertes Lead-Volumen", industry: "Immobilien" },
      { metric: "-40%", label: "Cost per Acquisition", industry: "Einzelhandel" },
      { metric: "+120%", label: "Retargeting-Conversions", industry: "Kosmetik" },
      { metric: "2.5x ROAS", label: "Return on Ad Spend", industry: "Sport" },
    ],
    omnichannelServices: ["Google Ads", "Instagram Ads", "TikTok Ads", "CRO", "E-Mail-Marketing"],
    faq: [
      { q: "Benutzt noch jemand Facebook?", a: "Mit fast 3 Milliarden monatlich aktiven Nutzern weltweit bleibt Facebook das größte soziale Netzwerk. Plus umfasst Meta auch Instagram in denselben Kampagnen, was Ihnen Reichweite auf beiden Plattformen gibt." },
      { q: "Ich poste bereits auf Facebook, was macht Paid anders?", a: "Organische Posts erreichen 3-5% Ihrer Follower. Bezahlte Anzeigen erreichen genau die von Ihnen definierte Zielgruppe, potenziell Hunderttausende oder Millionen von Menschen, nicht nur die, die Ihnen bereits folgen." },
      { q: "Wie viel Budget brauche ich für Facebook Ads?", a: "Wir empfehlen mindestens 300-500 €/Monat an Werbeausgaben. Darunter sind die Daten für die Optimierung unzureichend. Die Ergebnisse verbessern sich nach 60 Tagen erheblich, wenn der Algorithmus Ihre Zielgruppe gelernt hat." },
      { q: "Funktioniert Facebook Ads für B2B?", a: "Ja, aber mit einer anderen Strategie. Wir targetieren nach Berufsbezeichnung, Branche und Unternehmensgröße. Für Enterprise-B2B kann LinkedIn effektiver sein, wir helfen Ihnen zu entscheiden, was für Ihr Unternehmen funktioniert." },
      { q: "Welche Inhalte muss ich vorbereiten?", a: "Wir kümmern uns um Strategie und Copy. Wir benötigen einige Bilder Ihrer Produkte/Dienstleistungen und optional ein kurzes Video (auch mit dem Handy gefilmt). Authentisches funktioniert auf Facebook besser als Perfektes." },
      { q: "Wie weiß ich, dass meine Anzeigen wirklich performen?", a: "Durch wöchentliche Berichte mit allen Metriken: Reichweite, Frequenz, Cost per Click, Cost per Lead, Cost per Sale und ROAS. Wir verbergen nichts, auch wenn die Ergebnisse nicht auf Maximalniveau sind, sind Sie der Erste, der es weiß." },
    ],
    testimonial: { quote: "6,2x ROAS bei unseren Black-Friday-Kampagnen. Nesco hat eine komplette Funnel-Strategie erstellt, die viel besser funktionierte als das, was wir intern taten.", name: "Bogdan R.", role: "Gründer, Naturkosmetik-Marke" },
    tools: ["Meta Ads Manager", "Meta Pixel", "Meta Business Suite", "Google Analytics 4", "Klaviyo"],
    toolsSectionTitle: "UNSERE TOOLS",
    freeAuditBadge: "Kostenloser Facebook Ads Audit Inklusive",
  },
};

// ─── E-commerce Stores ────────────────────────────────────────────────────────
export const ecommerceData: Record<"ro" | "en" | "de", ServicePageData> = {
  ro: {
    locale: "ro",
    breadcrumbCategory: "webdesign",
    hero: {
      badge: "Magazine Online",
      title: "Magazine Online care vând",
      subtitle:
        "Platforme de vânzări perfect adaptate care transformă vizitatorii în clienți fideli și cresc vânzările. Shopify, WooCommerce, Magento.",
    },
    problems: [
      { title: "Navigare complicată", desc: "Utilizatorii abandonează din cauza experienței slabe" },
      { title: "Design neatractiv", desc: "Site-ul nu reflectă calitatea produselor tale" },
      { title: "Încărcare lentă", desc: "Fiecare secundă în plus = conversii pierdute" },
      { title: "Checkout complicat", desc: "Coșuri abandonate la pasul final" },
    ],
    solutions: [
      { title: "Analiză și planificare", desc: "Înțelegem nevoile afacerii și comportamentul cumpărătorilor." },
      { title: "Design custom", desc: "Experiență vizuală unică, adaptată brandului tău." },
      { title: "Platforme top", desc: "Shopify, WooCommerce, Magento, alegem platforma potrivită." },
      { title: "Integrare completă", desc: "Plăți, livrări, CRM, ERP, totul integrat perfect." },
      { title: "Optimizare SEO", desc: "Structura site-ului optimizată pentru Google din ziua 1." },
      { title: "Instrumente business", desc: "Raportare avansată, email marketing, retargeting." },
    ],
    cases: [
      { metric: "+80% MoM", label: "Creștere vânzări", industry: "Fashion Store" },
      { metric: "+50% MoM", label: "Creștere vânzări", industry: "Bio Cosmetics" },
      { metric: "+40% MoM", label: "Creștere conversii", industry: "Sports Equipment" },
      { metric: "-35%", label: "Rata de abandon coș", industry: "Electronics" },
      { metric: "400%", label: "Creștere revenue în 12 luni", industry: "E-commerce Brand" },
      { metric: "10x", label: "Revenue de la $250K la $2.5M", industry: "DTC Brand" },
    ],
    omnichannelServices: ["Google Ads", "Facebook Ads", "Email Marketing", "CRO", "SEO"],
  },
  en: {
    locale: "en",
    breadcrumbCategory: "webdesign",
    hero: {
      badge: "E-commerce Stores",
      title: "Your sales never stop with a well-built online store",
      subtitle:
        "A well-built online store works for you 24/7, reaches customers across your country or Europe, and can grow exponentially without proportional costs. Stop limiting your business to four walls.",
    },
    problems: [
      { title: "Your physical store is limited by location and hours", desc: "A customer from another city can't buy from your local store. Opening hours limit sales. An online store eliminates all these limitations." },
      { title: "Sales fluctuate seasonally and you can't scale fast", desc: "Online, you can activate ad campaigns in 24 hours and reach tens of thousands of potential buyers. Offline, you're tied to foot traffic." },
      { title: "Customers research online before buying", desc: "73% of shoppers search online even when they buy offline. If you're not in e-commerce, you risk losing even existing customers who compare." },
      { title: "Your competitors already sell online", desc: "If your competitors have an online store and you don't, you're losing market share every day." },
    ],
    solutions: [
      { title: "We choose the right platform for you", desc: "Shopify for simplicity and scalability, WooCommerce for flexibility and lower costs, or custom for complex needs. We don't sell a standard platform, we choose the one that fits you." },
      { title: "UX design optimized for conversions", desc: "Not every online store sells well. Category structure, product pages, checkout, every element is designed to reduce friction and maximize order completion." },
      { title: "Complete integration with shipping and payment", desc: "We integrate with major courier services and configure card payments, cash on delivery, bank transfer. Everything works automatically." },
      { title: "SEO optimized from day 1", desc: "Category structure, product URLs, meta descriptions, everything configured for Google from day one. Customers find you organically, not just through ads." },
      { title: "Stock and order management", desc: "Simple admin panel: add products, update stock, process orders and track deliveries, without technical knowledge." },
      { title: "Ready for digital marketing", desc: "We integrate Google Analytics 4, Meta Pixel, Google Merchant Center for Shopping Ads. From day 1, you're ready to run effective ad campaigns." },
    ],
    cases: [
      { metric: "+80% MoM", label: "Sales growth", industry: "Fashion Store" },
      { metric: "+50% MoM", label: "Sales growth", industry: "Bio Cosmetics" },
      { metric: "+40% MoM", label: "Conversion rate growth", industry: "Sports Equipment" },
      { metric: "-35%", label: "Cart abandonment rate", industry: "Electronics" },
      { metric: "400%", label: "Revenue growth in 12 months", industry: "E-commerce Brand" },
      { metric: "10x", label: "Revenue from $250K to $2.5M", industry: "DTC Brand" },
    ],
    omnichannelServices: ["Google Ads", "Facebook Ads", "Email Marketing", "CRO", "SEO"],
    faq: [
      { q: "Shopify or WooCommerce, which is better?", a: "Depends on your business. Shopify: easy to manage, excellent support, fixed monthly costs (€29-299/month), ideal for 10-1000 products without an IT team. WooCommerce: more flexible, no transaction fees, higher initial cost, ideal if you need advanced customization or already have WordPress hosting." },
      { q: "How much does it cost to run an online store monthly?", a: "Monthly costs include: hosting (€20-100), platform (free with WooCommerce or €29-299 with Shopify), SSL certificate (free with Let's Encrypt), and optionally maintenance. Excluding advertising, an average store costs €50-200/month in operational costs." },
      { q: "How hard is it to add products and process orders?", a: "We provide complete training. Adding a product takes 5-10 minutes. Processing an order (confirmation, generating tracking) takes 2-3 minutes. Many processes can be automated (confirmation emails, tracking generation)." },
      { q: "How do I handle returns and shipping?", a: "We configure return policy (legally required, 14 days for online orders in EU), courier integration for automatic tracking generation. You can process all logistics from the admin panel." },
      { q: "Can I sell in other countries?", a: "Yes. We configure multi-currency, translations, and international shipping costs. Shopify Multi-Market or WooCommerce with dedicated plugins. We've launched stores that sell in 15+ European countries." },
      { q: "Will my store be visible on Google?", a: "Yes, but organic SEO takes 3-6 months to bring significant traffic. In parallel with SEO, we recommend Google Shopping Ads for immediate sales." },
    ],
    testimonial: { quote: "We went from €250K to €2.5M in annual revenue in 18 months. The online store Nesco built converted at 4.2%, well above industry average. The checkout flow made all the difference.", name: "Stefan M.", role: "Founder, fitness equipment brand" },
    freeAuditBadge: "Free E-commerce Audit Included",
  },
  de: {
    locale: "de",
    breadcrumbCategory: "webdesign",
    hero: {
      badge: "E-Commerce-Shops",
      title: "Ihr Umsatz stoppt nie mit einem gut aufgebauten Online-Shop",
      subtitle:
        "Ein gut aufgebauter Online-Shop arbeitet 24/7 für Sie, erreicht Kunden in ganz Deutschland oder Europa und kann exponentiell wachsen ohne proportionale Kosten. Hören Sie auf, Ihr Geschäft auf vier Wände zu beschränken.",
    },
    problems: [
      { title: "Ihr Ladengeschäft ist durch Standort und Öffnungszeiten begrenzt", desc: "Ein Kunde aus einer anderen Stadt kann nicht bei Ihnen einkaufen. Öffnungszeiten begrenzen Verkäufe. Ein Online-Shop beseitigt all diese Beschränkungen." },
      { title: "Umsätze schwanken saisonal und skalieren langsam", desc: "Online können Sie in 24 Stunden Werbekampagnen aktivieren und Zehntausende potenzielle Käufer erreichen. Offline sind Sie an den Standortverkehr gebunden." },
      { title: "Kunden recherchieren online, bevor sie kaufen", desc: "73% der Käufer suchen online, selbst wenn sie offline kaufen. Wenn Sie nicht im E-Commerce sind, riskieren Sie, selbst bestehende Kunden zu verlieren, die vergleichen." },
      { title: "Ihre Mitbewerber verkaufen bereits online", desc: "Wenn Ihre Konkurrenten einen Online-Shop haben und Sie nicht, verlieren Sie täglich Marktanteile." },
    ],
    solutions: [
      { title: "Wir wählen die richtige Plattform für Sie", desc: "Shopify für Einfachheit und Skalierbarkeit, WooCommerce für Flexibilität und niedrigere Kosten, oder Custom für komplexe Anforderungen. Wir verkaufen keine Standardplattform, wir wählen die, die zu Ihnen passt." },
      { title: "UX-Design für maximale Conversions", desc: "Nicht jeder Online-Shop verkauft gut. Kategoriestruktur, Produktseiten, Checkout, jedes Element ist darauf ausgelegt, Reibung zu reduzieren und Bestellabschlüsse zu maximieren." },
      { title: "Vollständige Integration mit Versand und Zahlung", desc: "Wir integrieren mit großen Versanddienstleistern und konfigurieren Kartenzahlung, Nachnahme, Banküberweisung. Alles funktioniert automatisch." },
      { title: "SEO von Tag 1 optimiert", desc: "Kategoriestruktur, Produkt-URLs, Meta-Descriptions, alles von Tag 1 für Google konfiguriert. Kunden finden Sie organisch, nicht nur über Anzeigen." },
      { title: "Bestands- und Auftragsverwaltung", desc: "Einfaches Admin-Panel: Produkte hinzufügen, Bestand aktualisieren, Bestellungen bearbeiten und Lieferungen verfolgen, ohne technische Kenntnisse." },
      { title: "Bereit für digitales Marketing", desc: "Wir integrieren Google Analytics 4, Meta Pixel, Google Merchant Center. Von Tag 1 sind Sie bereit, effektive Werbekampagnen zu schalten." },
    ],
    cases: [
      { metric: "+80% MoM", label: "Umsatzwachstum", industry: "Fashion-Shop" },
      { metric: "+50% MoM", label: "Umsatzwachstum", industry: "Bio-Kosmetik" },
      { metric: "+40% MoM", label: "Conversion-Rate-Wachstum", industry: "Sportausrüstung" },
      { metric: "-35%", label: "Warenkorbabbruchrate", industry: "Elektronik" },
      { metric: "400%", label: "Umsatzwachstum in 12 Monaten", industry: "E-Commerce-Marke" },
      { metric: "10x", label: "Umsatz von 250K$ auf 2,5M$", industry: "DTC-Marke" },
    ],
    omnichannelServices: ["Google Ads", "Facebook Ads", "E-Mail-Marketing", "CRO", "SEO"],
    faq: [
      { q: "Shopify oder WooCommerce, was ist besser?", a: "Abhängig von Ihrem Unternehmen. Shopify: einfach zu verwalten, exzellenter Support, feste monatliche Kosten (29-299 €/Monat), ideal für 10-1000 Produkte ohne IT-Team. WooCommerce: flexibler, keine Transaktionsgebühren, höhere Anfangskosten, ideal wenn Sie erweiterte Anpassungen benötigen oder bereits WordPress-Hosting haben." },
      { q: "Wie viel kostet es monatlich, einen Online-Shop zu betreiben?", a: "Monatliche Kosten umfassen: Hosting (20-100 €), Plattform (kostenlos mit WooCommerce oder 29-299 € mit Shopify), SSL-Zertifikat (kostenlos mit Let's Encrypt), und optional Wartung. Ohne Werbung kostet ein durchschnittlicher Shop 50-200 €/Monat an Betriebskosten." },
      { q: "Wie schwer ist es, Produkte hinzuzufügen und Bestellungen zu verarbeiten?", a: "Wir bieten vollständiges Training. Ein Produkt hinzuzufügen dauert 5-10 Minuten. Eine Bestellung zu bearbeiten dauert 2-3 Minuten. Viele Prozesse können automatisiert werden (Bestätigungs-E-Mails, Tracking-Generierung)." },
      { q: "Wie verwalte ich Rücksendungen und Versand?", a: "Wir konfigurieren die Rückgaberichtlinie (gesetzlich vorgeschrieben, 14 Tage für Online-Bestellungen in der EU), Versanddienstleister-Integration für automatische Tracking-Generierung. Sie können die gesamte Logistik aus dem Admin-Panel verwalten." },
      { q: "Kann ich in andere Länder verkaufen?", a: "Ja. Wir konfigurieren Multi-Currency, Übersetzungen und internationale Versandkosten. Shopify Multi-Market oder WooCommerce mit dedizierten Plugins. Wir haben Shops lanciert, die in 15+ europäischen Ländern verkaufen." },
      { q: "Wird mein Shop auf Google sichtbar sein?", a: "Ja, aber organisches SEO dauert 3-6 Monate, um signifikanten Traffic zu bringen. Parallel zu SEO empfehlen wir Google Shopping Ads für sofortige Verkäufe." },
    ],
    testimonial: { quote: "Wir gingen in 18 Monaten von 250.000 € auf 2,5 Mio. € Jahresumsatz. Der Online-Shop, den Nesco gebaut hat, konvertierte bei 4,2%, weit über dem Branchendurchschnitt.", name: "Stefan M.", role: "Gründer, Fitnessgeräte-Marke" },
    freeAuditBadge: "Kostenloses E-Commerce-Audit Inklusive",
  },
};

// ─── Email Marketing ──────────────────────────────────────────────────────────
export const emailMarketingData: Record<"ro" | "en" | "de", ServicePageData> = {
  ro: {
    locale: "ro",
    breadcrumbCategory: "digitalMarketing",
    hero: {
      badge: "Email Marketing",
      title: "Email Marketing cu ROI 42:1",
      subtitle:
        "Construiește relații durabile cu clienții și crește vânzările prin campanii de email marketing eficiente și personalizate.",
    },
    problems: [
      { title: "Rate de deschidere mici", desc: "Emailurile nu sunt citite de destinatari" },
      { title: "Rate de click scăzute", desc: "Conținutul nu motivează acțiunea" },
      { title: "Dezabonări frecvente", desc: "Lista de contacte se micșorează constant" },
      { title: "Lipsă personalizare", desc: "Mesaje generice care nu rezonează cu audiența" },
    ],
    solutions: [
      { title: "Segmentare avansată", desc: "Grupăm audiența în segmente precise pentru mesaje relevante." },
      { title: "Crearea conținutului", desc: "Copy și design care captează atenția și motivează acțiunea." },
      { title: "Personalizare mesaje", desc: "Fiecare email este adaptat comportamentului destinatarului." },
      { title: "Automatizări email", desc: "Secvențe automate care lucrează 24/7 pentru tine." },
      { title: "A/B Testing", desc: "Testăm subiecte, copy și design pentru rezultate maxime." },
      { title: "Raportare și analiză", desc: "Date clare despre ce funcționează și ce trebuie îmbunătățit." },
    ],
    cases: [
      { metric: "42:1 ROI", label: "Return pe investiție", industry: "Medie industrie" },
      { metric: "+25%", label: "Creștere comenzi repetate", industry: "Fashion (Ecommerce)" },
      { metric: "+50%", label: "Creștere MQL", industry: "IT Services (B2C)" },
      { metric: "+20%", label: "Creștere rezervări", industry: "Hotel (B2C)" },
      { metric: "+35%", label: "Rată de deschidere", industry: "SaaS Platform" },
      { metric: "-60%", label: "Reducere dezabonări", industry: "Retail" },
    ],
    omnichannelServices: ["Google Ads", "Facebook Ads", "CRM Solutions", "CRO", "Social Media"],
    faq: [
      { q: "La ce rată de deschidere pot să mă aștept?", a: "Media industriei este 20-25%. Clienții noștri obțin în medie 35-45% open rate prin segmentare corectă și subiecte testate." },
      { q: "Funcționează email marketing în 2026?", a: "Email-ul are cel mai mare ROI din toate canalele de marketing, 42:1 în medie. Nu este mort, este subutilizat de majoritatea business-urilor." },
      { q: "De câte emailuri am nevoie pe lună?", a: "Minimum 4 emailuri/lună pentru a rămâne relevant. Recomandăm 8-12 pentru o strategie completă cu nurturing, promotional și educational." },
    ],
    testimonial: { quote: "Lista noastră de 8000 de abonați genera aproape nimic. Acum generează 15% din totalul revenue-ului lunar prin secvențele pe care le-a construit Nesco.", name: "Thomas K.", role: "Owner, lanț de retail Germania" },
    tools: ["Klaviyo", "Mailchimp", "ActiveCampaign", "Google Analytics 4", "Zapier"],
    toolsSectionTitle: "INSTRUMENTELE PE CARE LE FOLOSIM",
    freeAuditBadge: "Audit Email Marketing Gratuit Inclus",
  },
  en: {
    locale: "en",
    breadcrumbCategory: "digitalMarketing",
    hero: {
      badge: "Email Marketing",
      title: "Email Marketing with 42:1 ROI",
      subtitle:
        "Build lasting relationships with your customers and increase your sales through efficient and personalized email marketing campaigns.",
    },
    problems: [
      { title: "Low open rates", desc: "Emails not read by recipients" },
      { title: "Low click rates", desc: "Content doesn't motivate action" },
      { title: "Frequent unsubscribes", desc: "Contact list constantly shrinking" },
      { title: "Lack of personalization", desc: "Generic messages that don't resonate" },
    ],
    solutions: [
      { title: "Advanced segmentation", desc: "We group the audience into precise segments for relevant messages." },
      { title: "Content creation", desc: "Copy and design that capture attention and motivate action." },
      { title: "Message personalization", desc: "Each email is adapted to the recipient's behavior." },
      { title: "Email automation", desc: "Automatic sequences that work 24/7 for you." },
      { title: "A/B Testing", desc: "We test subjects, copy and design for maximum results." },
      { title: "Reporting & analysis", desc: "Clear data about what works and what needs improvement." },
    ],
    cases: [
      { metric: "42:1 ROI", label: "Return on investment", industry: "Industry average" },
      { metric: "+25%", label: "Repeat orders increase", industry: "Fashion (Ecommerce)" },
      { metric: "+50%", label: "MQL increase", industry: "IT Services (B2C)" },
      { metric: "+20%", label: "Bookings increase", industry: "Hotel (B2C)" },
      { metric: "+35%", label: "Open rate increase", industry: "SaaS Platform" },
      { metric: "-60%", label: "Unsubscribe reduction", industry: "Retail" },
    ],
    omnichannelServices: ["Google Ads", "Facebook Ads", "CRM Solutions", "CRO", "Social Media"],
    faq: [
      { q: "What open rate can I expect?", a: "The industry average is 20-25%. Our clients achieve an average 35-45% open rate through proper segmentation and tested subject lines." },
      { q: "Does email marketing still work in 2026?", a: "Email has the highest ROI of all marketing channels, 42:1 on average. It's not dead, it's underutilized by most businesses." },
      { q: "How many emails do I need per month?", a: "Minimum 4 emails/month to stay relevant. We recommend 8-12 for a complete strategy with nurturing, promotional, and educational content." },
    ],
    testimonial: { quote: "Our list of 8,000 subscribers was generating almost nothing. Now it generates 15% of total monthly revenue through the sequences Nesco built.", name: "Thomas K.", role: "Owner, retail chain Germany" },
    tools: ["Klaviyo", "Mailchimp", "ActiveCampaign", "Google Analytics 4", "Zapier"],
    toolsSectionTitle: "TOOLS WE USE",
    freeAuditBadge: "Free Email Marketing Audit Included",
  },
  de: {
    locale: "de",
    breadcrumbCategory: "digitalMarketing",
    hero: {
      badge: "E-Mail-Marketing",
      title: "E-Mail-Marketing mit 42:1 ROI",
      subtitle:
        "Bauen Sie dauerhafte Beziehungen zu Ihren Kunden auf und steigern Sie Ihren Umsatz durch effiziente und personalisierte E-Mail-Marketing-Kampagnen.",
    },
    problems: [
      { title: "Niedrige Öffnungsraten", desc: "E-Mails werden von Empfängern nicht gelesen" },
      { title: "Niedrige Klickraten", desc: "Inhalt motiviert keine Aktion" },
      { title: "Häufige Abmeldungen", desc: "Kontaktliste schrumpft ständig" },
      { title: "Mangelnde Personalisierung", desc: "Generische Nachrichten, die nicht resonieren" },
    ],
    solutions: [
      { title: "Erweiterte Segmentierung", desc: "Wir gruppieren die Zielgruppe in präzise Segmente für relevante Nachrichten." },
      { title: "Inhaltserstellung", desc: "Copy und Design, die Aufmerksamkeit erregen und zur Aktion motivieren." },
      { title: "Nachrichtenpersonalisierung", desc: "Jede E-Mail ist dem Verhalten des Empfängers angepasst." },
      { title: "E-Mail-Automatisierung", desc: "Automatische Sequenzen, die 24/7 für Sie arbeiten." },
      { title: "A/B-Testing", desc: "Wir testen Betreffzeilen, Copy und Design für maximale Ergebnisse." },
      { title: "Reporting & Analyse", desc: "Klare Daten darüber, was funktioniert und was verbessert werden muss." },
    ],
    cases: [
      { metric: "42:1 ROI", label: "Return on Investment", industry: "Branchendurchschnitt" },
      { metric: "+25%", label: "Steigerung Wiederholungsbestellungen", industry: "Fashion (E-Commerce)" },
      { metric: "+50%", label: "MQL-Steigerung", industry: "IT-Services (B2C)" },
      { metric: "+20%", label: "Buchungssteigerung", industry: "Hotel (B2C)" },
      { metric: "+35%", label: "Öffnungsratensteigerung", industry: "SaaS-Plattform" },
      { metric: "-60%", label: "Abmeldungsreduzierung", industry: "Einzelhandel" },
    ],
    omnichannelServices: ["Google Ads", "Facebook Ads", "CRM-Lösungen", "CRO", "Social Media"],
    faq: [
      { q: "Welche Öffnungsrate kann ich erwarten?", a: "Der Branchendurchschnitt liegt bei 20-25%. Unsere Kunden erzielen durchschnittlich 35-45% Öffnungsrate durch korrekte Segmentierung und getestete Betreffzeilen." },
      { q: "Funktioniert E-Mail-Marketing im Jahr 2026 noch?", a: "E-Mail hat den höchsten ROI aller Marketing-Kanäle, durchschnittlich 42:1. Es ist nicht tot, es wird von den meisten Unternehmen zu wenig genutzt." },
      { q: "Wie viele E-Mails brauche ich pro Monat?", a: "Mindestens 4 E-Mails/Monat, um relevant zu bleiben. Wir empfehlen 8-12 für eine vollständige Strategie mit Nurturing, Promotions und edukativen Inhalten." },
    ],
    testimonial: { quote: "Unsere Liste mit 8.000 Abonnenten generierte fast nichts. Jetzt generiert sie 15% des monatlichen Gesamtumsatzes durch die Sequenzen, die Nesco aufgebaut hat.", name: "Thomas K.", role: "Inhaber, Einzelhandelskette Deutschland" },
    tools: ["Klaviyo", "Mailchimp", "ActiveCampaign", "Google Analytics 4", "Zapier"],
    toolsSectionTitle: "UNSERE TOOLS",
    freeAuditBadge: "Kostenloses E-Mail-Marketing-Audit Inklusive",
  },
};

// ─── CRO Solutions ────────────────────────────────────────────────────────────
export const croData: Record<"ro" | "en" | "de", ServicePageData> = {
  ro: {
    locale: "ro",
    breadcrumbCategory: "digitalMarketing",
    hero: {
      badge: "CRO Solutions",
      title: "CRO, Mai multe conversii, același buget",
      subtitle:
        "Transformăm mai mulți vizitatori în clienți plătitori și maximizăm profitul prin optimizarea continuă a site-ului tău.",
    },
    problems: [
      { title: "Trafic mare, vânzări mici", desc: "Mii de vizitatori care nu cumpără" },
      { title: "Rata mare de abandon coș", desc: "Clienții pleacă înainte de finalizare" },
      { title: "Lead-uri necalificate", desc: "Formulare completate de oameni nepotriviți" },
      { title: "CPA ridicat", desc: "Costul per achiziție depășește bugetul" },
    ],
    solutions: [
      { title: "Analiză performanță", desc: "Identificăm exact unde și de ce pleacă utilizatorii." },
      { title: "Audit UX/UI", desc: "Evaluăm experiența utilizatorului și identificăm blocajele." },
      { title: "A/B și Testare multivariată", desc: "Testăm variante pentru a găsi ce convertește mai bine." },
      { title: "Optimizare landing page", desc: "Paginile de destinație construite pentru conversii maxime." },
      { title: "Personalizare conținut", desc: "Mesaje adaptate pentru fiecare segment de audiență." },
      { title: "Monitorizare & Raportare", desc: "Urmărim progresul și ajustăm continuu." },
    ],
    cases: [
      { metric: "35% mai mic", label: "Rata de abandon coș", industry: "Electronics (Ecommerce)" },
      { metric: "+50%", label: "Creștere demo-uri programate", industry: "SaaS (Software)" },
      { metric: "+135%", label: "Creștere abonați", industry: "Blog (Cooking)" },
      { metric: "+40%", label: "Creștere rata de conversie", industry: "Lead Gen Website" },
      { metric: "2x", label: "Rata de conversie în 1 an", industry: "Medie industrie" },
      { metric: "+25%", label: "Creștere AOV", industry: "E-commerce Fashion" },
    ],
    omnichannelServices: ["Google Ads", "Facebook Ads", "SEO", "Email Marketing", "Web Design"],
    faq: [
      { q: "Cum știți ce trebuie optimizat pe site-ul meu?", a: "Începem cu analiza datelor, heatmaps, session recordings, funnel analysis în Google Analytics. Datele dictează ce testăm, nu opinia noastră." },
      { q: "Cât de mult poate crește rata de conversie?", a: "Îmbunătățiri de 20-50% sunt realiste în primele 90 de zile. Am obținut și creșteri de 200%+ pentru clienți cu site-uri cu probleme majore de UX." },
      { q: "Ce este un A/B test și cât durează?", a: "Rulăm simultan două versiuni ale aceleiași pagini pentru a vedea care convertește mai bine. Durata: minimum 2 săptămâni sau 1000 vizitatori per variantă." },
    ],
    testimonial: { quote: "Am trecut de la 1.2% la 3.8% rată de conversie pe pagina de produs în 60 de zile. Simplu matematică: același trafic, de 3x mai multe vânzări.", name: "Sarah L.", role: "E-commerce Manager, echipamente sportive" },
    tools: ["Hotjar", "Microsoft Clarity", "Google Optimize", "Google Analytics 4", "VWO"],
    toolsSectionTitle: "INSTRUMENTELE PE CARE LE FOLOSIM",
    freeAuditBadge: "Audit CRO Gratuit Inclus",
  },
  en: {
    locale: "en",
    breadcrumbCategory: "digitalMarketing",
    hero: {
      badge: "CRO Solutions",
      title: "CRO, More conversions, same budget",
      subtitle:
        "Turn more visitors into paying customers and maximize your profit through continuous optimization of your website.",
    },
    problems: [
      { title: "High traffic, low sales", desc: "Thousands of visitors who don't buy" },
      { title: "High cart abandonment", desc: "Customers leave before completing purchase" },
      { title: "Unqualified leads", desc: "Forms completed by wrong people" },
      { title: "High CPA", desc: "Cost per acquisition exceeds budget" },
    ],
    solutions: [
      { title: "Performance analysis", desc: "We identify exactly where and why users leave." },
      { title: "UX/UI audit", desc: "We evaluate user experience and identify blockers." },
      { title: "A/B & multivariate testing", desc: "We test variants to find what converts better." },
      { title: "Landing page optimization", desc: "Destination pages built for maximum conversions." },
      { title: "Content personalization", desc: "Messages adapted for each audience segment." },
      { title: "Monitoring & Reporting", desc: "We track progress and adjust continuously." },
    ],
    cases: [
      { metric: "35% lower", label: "Cart abandonment rate", industry: "Electronics (Ecommerce)" },
      { metric: "+50%", label: "Demo bookings increase", industry: "SaaS (Software)" },
      { metric: "+135%", label: "Subscriber increase", industry: "Blog (Cooking)" },
      { metric: "+40%", label: "Conversion rate increase", industry: "Lead Gen Website" },
      { metric: "2x", label: "Conversion rate in 1 year", industry: "Industry average" },
      { metric: "+25%", label: "AOV increase", industry: "E-commerce Fashion" },
    ],
    omnichannelServices: ["Google Ads", "Facebook Ads", "SEO", "Email Marketing", "Web Design"],
    faq: [
      { q: "How do you know what needs to be optimized on my site?", a: "We start with data analysis, heatmaps, session recordings, funnel analysis in Google Analytics. Data dictates what we test, not our opinion." },
      { q: "How much can the conversion rate increase?", a: "Improvements of 20-50% are realistic in the first 90 days. We've also achieved 200%+ increases for clients with sites that had major UX issues." },
      { q: "What is an A/B test and how long does it take?", a: "We run two versions of the same page simultaneously to see which converts better. Duration: minimum 2 weeks or 1,000 visitors per variant." },
    ],
    testimonial: { quote: "We went from 1.2% to 3.8% conversion rate on the product page in 60 days. Simple math: same traffic, 3x more sales.", name: "Sarah L.", role: "E-commerce Manager, sports equipment" },
    tools: ["Hotjar", "Microsoft Clarity", "Google Optimize", "Google Analytics 4", "VWO"],
    toolsSectionTitle: "TOOLS WE USE",
    freeAuditBadge: "Free CRO Audit Included",
  },
  de: {
    locale: "de",
    breadcrumbCategory: "digitalMarketing",
    hero: {
      badge: "CRO-Lösungen",
      title: "CRO, Mehr Conversions, gleiches Budget",
      subtitle:
        "Verwandeln Sie mehr Besucher in zahlende Kunden und maximieren Sie Ihren Gewinn durch kontinuierliche Optimierung Ihrer Website.",
    },
    problems: [
      { title: "Hoher Traffic, niedrige Verkäufe", desc: "Tausende Besucher, die nicht kaufen" },
      { title: "Hohe Warenkorbabbruchrate", desc: "Kunden verlassen vor dem Abschluss" },
      { title: "Unkqualifizierte Leads", desc: "Formulare von falschen Personen ausgefüllt" },
      { title: "Hohe CPA", desc: "Cost per Acquisition überschreitet Budget" },
    ],
    solutions: [
      { title: "Leistungsanalyse", desc: "Wir identifizieren genau, wo und warum Nutzer abspringen." },
      { title: "UX/UI-Audit", desc: "Wir bewerten die Nutzererfahrung und identifizieren Blockaden." },
      { title: "A/B- & Multivariates Testing", desc: "Wir testen Varianten, um zu finden, was besser konvertiert." },
      { title: "Landing-Page-Optimierung", desc: "Zielseiten für maximale Conversions gebaut." },
      { title: "Inhaltspersonalisierung", desc: "Nachrichten für jedes Zielgruppensegment angepasst." },
      { title: "Monitoring & Reporting", desc: "Wir verfolgen den Fortschritt und passen kontinuierlich an." },
    ],
    cases: [
      { metric: "35% niedriger", label: "Warenkorbabbruchrate", industry: "Elektronik (E-Commerce)" },
      { metric: "+50%", label: "Demo-Buchungssteigerung", industry: "SaaS (Software)" },
      { metric: "+135%", label: "Abonnentensteigerung", industry: "Blog (Kochen)" },
      { metric: "+40%", label: "Conversion-Rate-Steigerung", industry: "Lead-Gen-Website" },
      { metric: "2x", label: "Conversion-Rate in 1 Jahr", industry: "Branchendurchschnitt" },
      { metric: "+25%", label: "AOV-Steigerung", industry: "E-Commerce Fashion" },
    ],
    omnichannelServices: ["Google Ads", "Facebook Ads", "SEO", "E-Mail-Marketing", "Webdesign"],
    faq: [
      { q: "Woher wissen Sie, was auf meiner Website optimiert werden muss?", a: "Wir beginnen mit der Datenanalyse, Heatmaps, Session-Recordings, Funnel-Analyse in Google Analytics. Daten bestimmen, was wir testen, nicht unsere Meinung." },
      { q: "Wie stark kann die Conversion-Rate steigen?", a: "Verbesserungen von 20-50% sind in den ersten 90 Tagen realistisch. Wir haben auch 200%+ Steigerungen für Kunden mit Websites mit schwerwiegenden UX-Problemen erzielt." },
      { q: "Was ist ein A/B-Test und wie lange dauert er?", a: "Wir führen zwei Versionen derselben Seite gleichzeitig aus, um zu sehen, welche besser konvertiert. Dauer: mindestens 2 Wochen oder 1.000 Besucher pro Variante." },
    ],
    testimonial: { quote: "Wir sind von 1,2% auf 3,8% Conversion-Rate auf der Produktseite in 60 Tagen gegangen. Einfache Mathematik: gleicher Traffic, 3x mehr Verkäufe.", name: "Sarah L.", role: "E-Commerce-Managerin, Sportausrüstung" },
    tools: ["Hotjar", "Microsoft Clarity", "Google Optimize", "Google Analytics 4", "VWO"],
    toolsSectionTitle: "UNSERE TOOLS",
    freeAuditBadge: "Kostenloses CRO-Audit Inklusive",
  },
};
